### ISSUE TITLE
Make VS Code theme have same syntax highlighting as nvim

### ISSUE THREAD

**Issue by codeonblocks** [catppuccin/vscode#101]
I've noticed that the VS Code theme's syntax highlighting looks much different from others like NeoVim. Why is that?

How do we make it have the same syntax highlighting as the `nvim` one? Can you make it look like `nvim`?

It should look like the image below.
![themes](https://github.com/catppuccin/vscode/assets/32179921/a15919aa-f0b3-4afd-b730-7fc508db686a)

**Comment by nekowinston** [comment]
Duplicate of #62.

The underlying Syntax highlighting of this plugin hasn't changed in 9 months. (#24)
I've done some development on the plugin side of things, but personally don't use VSCode; I don't have much motivation to continue work on #53, and would be happy for someone else to continue to work on it.

**Comment by codeonblocks** [comment]
Rip. Do you know of a guide anywhere for changing the colors of the various possible parts of the syntax highlighting?
