### ISSUE TITLE
arbitrary color for accentColor 

### ISSUE THREAD

**Issue by mil-ad** [catppuccin/vscode#108]
When I try setting `accentColor` to a hex code I see this warning:

```
Value is not accepted. Valid values: "rosewater", "flamingo", "pink", "mauve", "red", "maroon", "peach", "yellow", "green", "teal", "sky", "sapphire", "blue", "lavender".(1)
```

Is it possible to use an arbitrary color for this property?

**Comment by justTOBBI** [comment]
Hey,
I think you might be able to overwrite the value in the settings.json after setting one color.
Not exactly sure, but from my understanding that should work.
For instructions read the README.md

**Comment by nekowinston** [comment]
It's intended to be overwritten like so:
```json
  "catppuccin.accentColor": "pink",
  "catppuccin.colorOverrides": {
    "mocha": {
      "pink": "#ff69b4"
    }
  },
  ```
![image](https://github.com/catppuccin/vscode/assets/79978224/1a8f8a71-4b36-4a80-a12b-8d722e5465ba)

**Comment by mil-ad** [comment]
that works, thanks
