### ISSUE TITLE
Text selection background not present when right clicking in VSCode

### ISSUE THREAD

**Issue by mwsealey** [catppuccin/vscode#110]
I'm really confused here, somehow when I select some text and then right click to do something, Catppuccin removes the selection highlight:

![image](https://github.com/catppuccin/vscode/assets/469228/a905085b-4db5-4a4d-afff-a39cd7432cd3)

![image](https://github.com/catppuccin/vscode/assets/469228/c4459830-8440-45c8-8629-9bd1c6a55702)

Compare and contrast Dark Modern which is deemphasising the highlight somehow (it gets less 'pop')

![image](https://github.com/catppuccin/vscode/assets/469228/4a995325-8e10-41bc-8d28-585487088e13)

![image](https://github.com/catppuccin/vscode/assets/469228/680bb8f1-9930-4f01-850b-b422207a5b0e)

I couldn't figure out what color name or theme item or whatever corresponds to this behavior whatsoever, but it is jarring to go refactor something or need a menu item and you don't have that visual confirmation that the selection you selected is still selected..

**Comment by suppayami** [comment]
It's on `editor.inactiveSelectionBackground` I think @nekowinston 

https://github.com/catppuccin/vscode/blob/7f63767c1877f18c0408457cb7b2972e2fb1d612/src/theme/uiColors.ts#L250C43-L250C54
