### ISSUE TITLE
Some colors are not rendered properly after upgrading to 3.0

### ISSUE THREAD

**Issue by NikarashiHatsu** [catppuccin/vscode#141]
Here's an example of my PHP code snippet using the Catppuccin v2.9

<img width="619" alt="Screenshot 2023-09-03 at 18 08 44" src="https://github.com/catppuccin/visual-studio/assets/43662951/379c5ac8-1a19-4cec-b531-584fa277871a">

But after upgrading it to 3.0, some of the colors are missing

<img width="615" alt="Screenshot 2023-09-03 at 18 09 06" src="https://github.com/catppuccin/visual-studio/assets/43662951/3f5353ed-89e8-4b41-9d0c-04f393c85beb">

I'm wondering whether this is an issue or this is just how the color palette works, but I do prefer v2.

**Comment by NikarashiHatsu** [comment]
Thank you! It definitely looks better.

**Comment by quenbyako** [comment]
@nekowinston since golang theme also became a total shit after 3.0.0 — how can i contribute to theme definition? It looks like the syntax highlight broke after migration, or idk... Can i help somehow to update it for previous flavor?

**Comment by nekowinston** [comment]
@quenbyako have you tried with
```json
{
  "gopls": {
    "ui.semanticTokens": true
  },
}
```
from the [official Go extension](https://marketplace.visualstudio.com/items?itemName=golang.Go)?

I just gave go another look and pushed a few changes (https://github.com/catppuccin/vscode/commit/abf9b40b56e246cb1d8958fbd566d6ed5e839d7b).

**Comment by quenbyako** [comment]
@nekowinston yeaaaaaah, with this setting palette became less shitty, thanks 😆  Thank you, at least now i can code without blood in the eyes :) 

What do you think about adding this info somewhere... somewhere? In readme, or in faq.md or sorta, cause i asked all my team members in my company and no one knew that you need to path settings a bit for gopls :(

**Comment by quenbyako** [comment]
Ah, sorry, cancel that, in go extension readme there is already a warning, that you need to do it manually, cancel my question
