### ISSUE TITLE
Bold text not working properly after updating to the latest version

### ISSUE THREAD

**Issue by TheRustyPickle** [catppuccin/vscode#144]
After updating the extension to 3.0.1, it's not rendering bold text anywhere. Below are the screenshots (Rust language)

Version: 2.9.0
![Screenshot from 2023-09-04 01-28-11](https://github.com/catppuccin/vscode/assets/35862475/eb16c654-0447-4978-a9e6-5a44123077a5)

Version: 3.0.1
![Screenshot from 2023-09-04 01-27-46](https://github.com/catppuccin/vscode/assets/35862475/6f044dc2-899f-404e-a8ea-dc016e6c8233)

**Comment by nekowinston** [comment]
The new syntax highlighting is intentionally not using bold keywords in most cases, exceptions are Markdown and other Markup languages, e.g. for `**bold**`.
