### ISSUE TITLE
Python f-strings colour

### ISSUE THREAD

**Issue by ale-dg** [catppuccin/vscode#148]
Hi,

With version 3.1.0, the f-strings in Python do not change colour of the 'f'. See screenshot below. They keep the same colour as the normal string:
![Screenshot 2023-09-03 at 21 09 11](https://github.com/catppuccin/vscode/assets/106413328/bd6c9721-3aa9-4bfe-bfe7-e4cb09673034)

Best

**Comment by nekowinston** [comment]
We made this change intentionally to be closer to Neovim & IntelliJ PyCharm in this case.

If you're happy with the other changes, you can override just the `storage.type.string` scope for python:
```json
  "editor.tokenColorCustomizations": {
    "[Catppuccin Mocha]": {
      "textMateRules": [
        {
          "name": "Python f-strings",
          "scope": "source.python storage.type.string",
          "settings": {
            "foreground": "#f5c2e7",
            "fontStyle": ""
          }
        }
      ]
    }
  }
  ```

**Comment by ale-dg** [comment]
Hi @nekowinston ,

Thanks for the quick answer. Thought it was an issue. I'll override it through the settings json then.

I am closing the issue now.

Best,
