### ISSUE TITLE
PHP lacks syntax highlighting

### ISSUE THREAD

**Issue by kimael-code** [catppuccin/vscode#150]
Variable identifiers look truly ugly now and has no syntax highlighting 😭.

This happens in PHP.

**Comment by nekowinston** [comment]
It's a bit hard to say without a screenshot, but I think it's intentional, like https://github.com/catppuccin/vscode/issues/141#issuecomment-1704291091

**Comment by kimael-code** [comment]
Indeed... here are some screenshots with the Machiatto version (my favorite).


The new installed version (the 😭 version):
![Screenshot_20230904_132556](https://github.com/catppuccin/vscode/assets/78669175/0865489b-5bf3-467a-87d7-74b8c1539d90)


The old version (the 😊 version):
![Screenshot_20230904_132918](https://github.com/catppuccin/vscode/assets/78669175/ecdc7b08-c89f-4f6f-b3af-0c5f4bd540cd)

**Comment by NikarashiHatsu** [comment]
Sorry to bump this, come to think of it, 2.9x version looks better than 3.x. A question for @nekowinston (sorry for mentioning), is it because the palette changed or it is caused by incorrect settings on Vscode?

**Comment by nekowinston** [comment]
Neither, this was an intenional change: https://github.com/catppuccin/vscode/issues/62

**Comment by NikarashiHatsu** [comment]
That's pretty much reasonable change. Thanks for the answer!
