### ISSUE TITLE
Syntax highlighting stopped working in julia after update

### ISSUE THREAD

**Issue by moshialam** [catppuccin/vscode#151]
Hi 

I just reloaded my vscode environment after updating the catppuccin theme. Previously syntax highlighting used to work for julia, but after the update, it is no longer working. 

Thanks!

**Comment by nekowinston** [comment]
Hey there, thanks for the issue!

I just added initial support for Julia;
as I'm not really familiar with the language, I just looked at https://github.com/samuelcolvin/JuliaByExample and highlighted whatever I could find.

The update's live (3.2.0), if you see anything that could be improved, please let me know.

**Comment by moshialam** [comment]
Thanks so much for the prompt update! Everything looks great to me. One suggestion is syntax highlighting for julia symbols. If I am not mistaken, then the previous version of catppuccin used to have it. To give an example from the link you posted, if you look at the last section on DataFrames, column names are specified as symbols. For example, in `showln(by(iris, :Species, df -> size(df, 1)))` the column name `:Species` used to have a syntax highlight. 

Thanks so much!
