### ISSUE TITLE
Typescript's "console.log" is no longer highlighted

### ISSUE THREAD

**Issue by ptrxyz** [catppuccin/vscode#157]
Wihle I admit that version 3 of the theme looks so much better, I liked that in version 2.9.0 (and before), `console` was highlighted slightly red. This is no longer the case. Compare these two:

![image](https://github.com/catppuccin/vscode/assets/209056/58e5b202-72cf-4224-ae3d-7c04c35185bd) 
(new, Version 3)

vs:

![image](https://github.com/catppuccin/vscode/assets/209056/5fc15b0d-1165-4e06-8d5c-6eb49ce4cd3a)
(old, Version 2)

Can I somehow get the old style for `console` back? Maybe with overrides?

**Comment by ptrxyz** [comment]
One more thing came to my attention: when reloading the window, it looks as if `console.log` is actually highlighted as in the old version 2, but after a blink of an eye it turns to "non-highlighted" gray. Could that be related to VSCodes semantic token colorization?

I am using VSCode version 1.81.1 and Catppuccin 3.2.1

**Comment by nekowinston** [comment]
>One more thing came to my attention: when reloading the window, it looks as if console.log is actually highlighted as in the old version 2, but after a blink of an eye it turns to "non-highlighted" gray. Could that be related to VSCodes semantic token colorization?

Yes, semantic highlighting doesn't a scope I can use here, sadly. The semantic token `console.log()` is returning for me is `variable` which, when it arguably should have a `builtin` token modifier.

**Comment by nekowinston** [comment]
@ptrxyz I found out that some people (including me after some update, and I cannot find out which one it was) *do* have the `console` part highlighted!

![](https://cdn.discordapp.com/attachments/1091696312870764544/1150199221484540056/2023-09-10-0040542x.png)

This token has been set in the theme since 3.0.0, and I don't understand why it's suddenly working for me:
https://github.com/catppuccin/vscode/blob/64a2e7bbb0c1d7fd336ea895415a34e10cbb7d0d/src/theme/semanticTokens.ts#L9

It might be worth trying again.

**Comment by ptrxyz** [comment]
True, somehow it's fixed by now.

In case it breaks again, I worked around the bug using this snippet in my settings.json:

```json
    "editor.tokenColorCustomizations": {
        "[Catppuccin Macchiato]": {
            "textMateRules": [
                {
                    "name": "Other Variables",
                    "scope": ["variable.other"],
                    "settings": {
                        "foreground": "#F2CECF",
                        "fontStyle": ""
                    }
                }
            ]
        }
    },
```

**Comment by ptrxyz** [comment]
Hm, this is present again in 3.3.0 (console.log is not highlighted)...



![image](https://github.com/catppuccin/vscode/assets/209056/dc948550-75f4-4bef-b6d6-28bbf6959852)

**Comment by ptrxyz** [comment]
Can you tell me what tool you use to get those debug info? Maybe I can find out more what's wrong here.

**Comment by ptrxyz** [comment]
I also figured that I have to change the scope: I am setting the color on `variable.other` and you seem to use `variable.other.readwrite.ts`. Could it be related to that?

**Comment by nekowinston** [comment]
> Can you tell me what tool you use to get those debug info? Maybe I can find out more what's wrong here.

That's "inspect tokens" in the command palette.

> Hm, this is present again in 3.3.0 (console.log is not highlighted)...

Sadly, TextMate tokens don't apply when Semantic Highlighting is being applied. If semantic highlighting sets detects `console` as a normal variable, there is no TextMate token that will ever be able to override it.
Semantic tokens are always preferred by VS Code.

It all depends on your repository settings, such as tsconfig, bundlers, etc. for things like `window` `console` etc. to be recognized as builtins.
