### ISSUE TITLE
No italics for keywords

### ISSUE THREAD

**Issue by codeonblocks** [catppuccin/vscode#158]
Whenever I select italics for keyword it doesn't work. Even if I set the following in VS Code `settings.json`, it doesn't work:

`"catppuccin.italicKeywords": true`

**Comment by codeonblocks** [comment]
> Whenever I select italics for keyword it doesn't work. Even if I set the following in VS Code `settings.json`, it doesn't work: 

`"catppuccin.italicKeywords": true`

**Comment by nekowinston** [comment]
This is directly related to #159 in your case, since changing options will need a successful recompile.
I opened #160 to get rid of the node:fs dependency & made some other improvements to the compiler, I hope that helps.
