### ISSUE TITLE
Not working properly & breaks VS Code

### ISSUE THREAD

**Issue by codeonblocks** [catppuccin/vscode#159]
For some reason, the theme is causing VS Code to break and it won't load the theme anymore. When I uninstall it everything works as normal, but when I try to reinstall it and apply the theme it says:

`Unable to load file:///home/user/.vscode/extensions/catppuccin.catppuccin-vsc-3.2.1/themes/macchiato.json: Problems parsing JSON theme file: Value expected`

**Comment by ptrxyz** [comment]
This happened to me too randomly. I figured that the file was 0 bytes and would thus not be a valid json file. Probably for caching reasons or so VSCode does not remove the extension folder when you uninstall. Try this:

- use VSCode to uninstall the extension
- delete `/home/user/.vscode/extensions/catppuccin.catppuccin-vsc-3.2.1/themes/macchiato.json` manually (`rm -r`)
- reinstall the extension

Worked for me.

**Comment by nekowinston** [comment]
Pretty confident that we found & fixed the issue for good with #168, I was finally able to troubleshoot with someone on Discord.
