### ISSUE TITLE
Activitus Icon Colours

### ISSUE THREAD

**Issue by KarimLeVallois** [catppuccin/vscode#16]
The icon colours on the Activitus statusbar extension come out incorrectly (grey on a pink background), so can I please request that the following is added to match them with the rest of the statusbar icons?

`"activitusbar.inactiveColour": "#302d41"`

**Comment by VictorTennekes** [comment]
I can't seem to recreate this issue, could you perhaps tell me how/add a screenshot?

<img width="153" alt="Screenshot 2022-02-22 at 09 18 40" src="https://user-images.githubusercontent.com/19930858/155090933-b503844e-f919-42b7-9fb3-71d9e003e5f0.png">

**Comment by KarimLeVallois** [comment]
That's weird, my statusbar is a pale pink?! I'll take another look once I'm home later, could just be my setup...

**Comment by VictorTennekes** [comment]
Could it have been that you hadn't opened a working folder yet? Visual Studio Code/ium displays a pink statusbar in the catppuccin theme to signify no working dir.

**Comment by KarimLeVallois** [comment]
That could very well be the case, but adding that override to settings fixed the white on pink issue I was having.

**Comment by VictorTennekes** [comment]
Ah yeah, saw what's wrong with it, Ill add it.

**Comment by KarimLeVallois** [comment]
Awesome, thanks!

**Comment by VictorTennekes** [comment]
Does it work with other themes for you? For me the icons blend into the no-folder statusbar regardless of the theme.

**Comment by KarimLeVallois** [comment]
Not noticed to be honest, tend to use Sublime Text over VSCode for most things. Perhaps the extension needs updating if that is the case?

**Comment by VictorTennekes** [comment]
Ah no that seemed to be an issue on my side, I'll add the line and update it on the marketplace.

**Comment by KarimLeVallois** [comment]
Nice one!

**Comment by VictorTennekes** [comment]
I've checked it some more and this is actually a settings option and not a color theme change I can make.

**Comment by KarimLeVallois** [comment]
Ah, that's a shame! Thanks for looking into it though, much appreciated.
