### ISSUE TITLE
Syntax highlighting broken for Scala in 3.X

### ISSUE THREAD

**Issue by piotrwieckiewicz** [catppuccin/vscode#161]
Hey! First of all - thank you very much for this awesome theme and your willingness to ensure consistency in colors between editors!

Unfortunately syntax highlighting for Scala files seems to be very... orange heavy when LSP (such as [Metals](https://github.com/scalameta/metals)) is enabled.
Take a look at this example:

| Without LSP | With LSP |
|-------------|----------|
| ![obraz](https://github.com/catppuccin/vscode/assets/62888911/c776590a-3d04-44b6-8c8a-5f8e36f855b6) | ![obraz](https://github.com/catppuccin/vscode/assets/62888911/f574e33d-1843-4563-9d77-6c217a3267f7) |

The example was taken from [here](https://github.com/sharkdp/bat/blob/master/tests/syntax-tests/source/Scala/ConcurrentEffectLaws.scala). Were these colors intended?

**Comment by nekowinston** [comment]
Thanks for the issue!
I wasn't aware that Scala also used Semantic highlighting, and just looked at the regular TextMate tokens, so I missed that one.

I'll have a look with LSP enabled, that's definitely too much orange 😅
