### ISSUE TITLE
Function calls are not highlighted in Go

### ISSUE THREAD

**Issue by kembo91** [catppuccin/vscode#162]
Catppuccin:
<img width="673" alt="image" src="https://github.com/catppuccin/vscode/assets/6001644/fbdb3542-408a-452f-9f67-ca4384559827">

Default:
<img width="673" alt="image" src="https://github.com/catppuccin/vscode/assets/6001644/8f2d8b7d-d7cb-44e5-b43b-603f8d3373ee">

In my case, function calls and type casts are not highlighted properly. Not sure if that's intended

**Comment by nekowinston** [comment]
Thanks for the issue, this one's already on my radar, i'll fix it with the next release 🙂 

There's a workaround I commented here, if you use gopls from the official extension: https://github.com/catppuccin/vscode/issues/141#issuecomment-1704443089

```jsonc
{
  "gopls": {
    "ui.semanticTokens": true
  },
}
```
