### ISSUE TITLE
Python type annotations in 3.x mix with parameter names

### ISSUE THREAD

**Issue by chmielcode** [catppuccin/vscode#163]
Since version 3.x type annotations in python are colored like parameter names. In my opinion 2.x version is much more readable. Is it possible to fix that or is it on purpose? 
2.x
![obraz](https://github.com/catppuccin/vscode/assets/45938987/b4af31a1-df22-4403-b5ff-dcd8b7889711)
3.x
![obraz](https://github.com/catppuccin/vscode/assets/45938987/3edb9216-092b-488c-b6f2-9edae0bc7f6e)

Thank you for your work. I really like your theme (before version 3.x) :)

**Comment by nekowinston** [comment]
Do you have semantic highlighting enabled? The type annotations should be `peach`.

**Comment by chmielcode** [comment]
I don't have semantic highlighting enabled since it generates other inconsistencies. After enabling it the same code looks like this, which is even worse for me.
![obraz](https://github.com/catppuccin/vscode/assets/45938987/639a8166-ccf7-4b34-89f1-9f4dd325c672)

3.x normal
![obraz](https://github.com/catppuccin/vscode/assets/45938987/8a4d681d-f4d2-4c9f-9a3d-fbfaa0f10c6c)

3.x semantic
![obraz](https://github.com/catppuccin/vscode/assets/45938987/59917e90-7b7d-4d86-8294-a70520605c95)

2.x normal
![obraz](https://github.com/catppuccin/vscode/assets/45938987/003c32d3-01ec-4b29-bc2f-53908a3c002a)

For me at least 2.x normal version looks much better.

**Comment by nekowinston** [comment]
The semantic highlighting screenshots here on 3.x are definitely what we're going for with this update.
