### ISSUE TITLE
Font used in screenshot

### ISSUE THREAD

**Issue by oguh43** [catppuccin/vscode#17]
Hi, what font did you use to make != appear as ![image](https://user-images.githubusercontent.com/13382592/157077607-44bf5ece-1518-48c1-8adf-bc1530276378.png)? thanks :)

**Comment by VictorTennekes** [comment]
It's JetBrains Mono with ligatures turned on :)

**Comment by oguh43** [comment]
Oh, thanks!

**Comment by adilJamshad** [comment]
How do i set `JetBrainsMono Nerd Font` as my font-family in this theme?

**Comment by VictorTennekes** [comment]
It's in the general settings of Visual Studio Code, the 3rd option from the top should be Font Family.
