### ISSUE TITLE
Nuxt custom component & props have identical colors

### ISSUE THREAD

**Issue by ghoshRitesh12** [catppuccin/vscode#172]
### For Nuxt's syntax highlighting, since version 3.x, the colors of custom components and props have become the same.

**Version 2.x preview**

![Screenshot 2023-09-12 000533](https://github.com/catppuccin/vscode/assets/101876769/edc09f07-d9c2-40e4-b08e-a7d4e91a0311)

**Version 3.x preview**

![Screenshot 2023-09-12 000628](https://github.com/catppuccin/vscode/assets/101876769/35cb50c9-e044-4132-8324-e91d0ad9c6a9)

I really love the themes provided by catppuccin, I just wish the props looked indifferent than components in version 3.x and I really liked the shade of yellow(maybe orange) in version 2.x

**Comment by nekowinston** [comment]
Thanks for the issue, I've adjusted the highlighting so it looks more like JSX and HTML:
![2023-09-11-211332@2x](https://github.com/catppuccin/vscode/assets/79978224/bb60bb81-762f-48fa-85b7-2245dbc908a1)

**Comment by ghoshRitesh12** [comment]
> Thanks for the issue, I've adjusted the highlighting so it looks more like JSX and HTML:
> ![2023-09-11-211332@2x](https://github.com/catppuccin/vscode/assets/79978224/bb60bb81-762f-48fa-85b7-2245dbc908a1)
> 

Hey that looks great, but the custom components had a different color than native html elements.

**Comment by nekowinston** [comment]
I adjusted it to keep it consistent with JSX, MDX, HTML; if you want to override the color, you can use
```json

  "editor.tokenColorCustomizations": {
    "[Catppuccin Mocha]": {
      "textMateRules": [
        {
          "name": "Vue components",
          "scope": "support.class.component.vue",
          "settings": {
            "foreground": "#b4befe",
            "fontStyle": ""
          }
        }
      ]
    }
  }
```
for example.

I might revisit Components later, but I'm personally pretty happy with the current highlighting.

**Comment by ghoshRitesh12** [comment]
> I adjusted it to keep it consistent with JSX, MDX, HTML; if you want to override the color, you can use
> ```json
> 
>   "editor.tokenColorCustomizations": {
>     "[Catppuccin Mocha]": {
>       "textMateRules": [
>         {
>           "name": "Vue components",
>           "scope": "support.class.component.vue",
>           "settings": {
>             "foreground": "#b4befe",
>             "fontStyle": ""
>           }
>         }
>       ]
>     }
>   }
> ```
> for example.
> 
> I might revisit Components later, but I'm personally pretty happy with the current highlighting.

Sounds good, thanks for a speedy fix 🙌🏼
