### ISSUE TITLE
Semantic Syntax Highlight not working in VSCode

### ISSUE THREAD

**Issue by kachidk** [catppuccin/vscode#179]
VSCode version: 1.82.2
Extension version: 3.3.0
Typescript version:  5.1.6
Volar version: 1.8.11

Semantic syntax highlighting not working for Typescript and Vue components
![image](https://github.com/catppuccin/vscode/assets/61981167/4946b064-87e5-4192-8788-e0fd331e63cb)

---

Meanwhile in Extension version: 2.9.0
![image](https://github.com/catppuccin/vscode/assets/61981167/e247952c-785c-4202-8802-f1a429009239)

**Comment by nekowinston** [comment]
Are you using [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) for TSX files in Vue? I've had a look at some source code, and it looks like their tsserver doesn't support semantic highlighting.

The normal textmate highlighting in your first screenshot seems fine to me.

**Comment by kachidk** [comment]
Volar doesn't support Semantic highlighting. But somehow textmate has been able to intelligently infer it.
It doesn't work even for React.

The first screenshot is React code with the current extension version (3.3.0) where the issue is.
The second screenshot is extension version (2.9.0) where there is no issue
The screenshots are both the same code but with different extension versions.

**Comment by nekowinston** [comment]
What do you expect from the semantic highlighting in this screenshot? Like I said, it seems fine to me.

**Comment by kachidk** [comment]
In previous versions Components are highlighted as Orange and html tags purple.

But now in the current version html tags and components are the same, even the coloring of the attributes are no longer the same as the previous versions
 
I specified the versions to help trace it

**Comment by nekowinston** [comment]
This was a deliberate decision, please see https://github.com/catppuccin/vscode/issues/172 & #62
