### ISSUE TITLE
Any plans for a light mode?

### ISSUE THREAD

**Issue by emma-alexandria** [catppuccin/vscode#180]
I know, I'm a weirdo, but I enjoy programming with light themes. Is there any plan to implement one? If not, I might make a PR if I end up being competent enough to make one.

**Comment by riichi67** [comment]
but... latte theme...

**Comment by isabelroses** [comment]
On the Catppuccin extension page you can click the `Set Color Theme` button from there you will get a drop down, like so
![image](https://github.com/catppuccin/vscode/assets/71222764/661a9d69-41a4-4db2-89d7-e77ebbdc341c)
From there choose latte.

**Comment by emma-alexandria** [comment]
Ah, thank you! For some reason Latte only showed up for me *specifically* under the `Set Color Theme` drop-down and not in my command palette.
