### ISSUE TITLE
Azure Data Studio compatibility 

### ISSUE THREAD

**Issue by Sinirlan** [catppuccin/vscode#184]
Not really an issue, just wanted to share information. The vsix package seems to be compatible with Azure Data Studio, new SQL tool from MS which aims to replace SQL Server Management Studio. I was able to install vsix package using manual installation and from the looks of things everything is working good, didn't noticed any glaring issues. Maybe would be worth to do some in depth testing and release as separate repo or leave note in current one.

**Comment by nekowinston** [comment]
Implemented in #230, waiting upstream on https://github.com/microsoft/azuredatastudio/pull/25077 so it shows up in the Marketplace Gallery.
