### ISSUE TITLE
Problems loading reference to json schema 

### ISSUE THREAD

**Issue by Eshanatnight** [catppuccin/vscode#197]
I am not sure if this is only a problem on my setup. But when I have the Theme Installed, and am trying to go into my vscode `settings.json` but I am getting a "error" and the json schema is not loading.

```
Problems loading reference 'https://raw.githubusercontent.com/catppuccin/vscode/main/schemas/colorOverrides.schema.json': Unable to load schema from 'https://raw.githubusercontent.com/catppuccin/vscode/main/schemas/colorOverrides.schema.json': connect ETIMEDOUT 49.44.79.236:443.(768)
```

**Comment by ghostx31** [comment]
Hi, it seems like your ISP (Jio in this case) is blocking raw.githubusercontent.com. 
Jio is known to block GitHub and related sites quite often.
