### ISSUE TITLE
Suggestions for accompanying Icon theme?

### ISSUE THREAD

**Issue by ghost** [catppuccin/vscode#20]

**Comment by nekowinston** [comment]
Just some feedback on this issue: We're looking into creating a Catppuccin-coloured fork of a popular icon set.
Please feel free to suggest sets which we could fork.

**Comment by mystrdat** [comment]
I would suggest Bearded Icons set.

**Comment by charlesphil** [comment]
I've used the ever-popular [Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme) for the longest time, and to be honest it would be very difficult for me to use anything else. However, the only downside with Material is that the colors sort of clash when I use it with Mocha. With Latte, though, the set works amazingly well. If there was a variation that worked with all four palettes, this would probably be my endgame setup.

**Comment by charlesphil** [comment]
Here's an example of what it looks like on Latte:
<img width="1820" alt="image" src="https://user-images.githubusercontent.com/71610407/189239856-e4a590ad-0975-4cc6-92da-5c1cfda1a1ac.png">

**Comment by charlesphil** [comment]
I saw this in the Discord server, but figured I'd comment on this issue as well, but it looks like someone has started making their own Catppuccin VSCode icons here: https://github.com/prazdevs/catppuccin-vscode-icons

**Comment by nekowinston** [comment]
We've since moved the Icon pack over to the org, and I've linked to it in the README with the latest release.

Since Catppuccin now has multiple Extensions in the Marketplace, I've also created an [Extension Pack](https://marketplace.visualstudio.com/items?itemName=catppuccin.catppuccin-vsc-pack) (I'll make it look nicer later today).
