### ISSUE TITLE
SASS language syntax coloring

### ISSUE THREAD

**Issue by mittalyashu** [catppuccin/vscode#21]
There seems to be problem with SASS language syntax colouring

* The property value has italics styles _(which should not happen)_
* From `line 9` to `line 16`, the property has different color comparing other lines

| SASS | CSS |
| --- | --- |
| <img width="560" alt="CleanShot 2022-04-17 at 10 12 01@2x" src="https://user-images.githubusercontent.com/29014463/163700808-32f15431-5df1-4375-8ff1-271ab58e46f1.png"> | <img width="556" alt="CleanShot 2022-04-17 at 10 12 07@2x" src="https://user-images.githubusercontent.com/29014463/163700816-6cfe79cb-d435-4319-bb45-6e871b571694.png"> |

**Comment by VictorTennekes** [comment]
Are you using any additional plugins for sass syntax highlighting?

**Comment by mittalyashu** [comment]
> Are you using any additional plugins for sass syntax highlighting?

Yes, I've this extension install `syler.sass-indented`

**Comment by VictorTennekes** [comment]
I think that might be changing it, when I had a quick peek it seemed the same.

**Comment by ghostx31** [comment]
Seems like an external plugin was causing this issue. 
Nonetheless, I had a look at sass highlighting and it works flawlessly with the Catppuccin 0.2.0 update so I'll be closing this issue for now.
