### ISSUE TITLE
Extension causes a annoying visual bug with the `.vscode/settings.json` file

### ISSUE THREAD

**Issue by Zliced13** [catppuccin/vscode#213]
Without Catppuccin:
![VSCode_old](https://github.com/catppuccin/vscode/assets/101912712/83d66558-1c91-4eac-8cde-089fa7340ac4)

WITH Catppuccin: 
![VSCode](https://github.com/catppuccin/vscode/assets/101912712/614fac63-99b6-4aa8-8386-bbec36a8bb1b)

--------

Is there a way to fix this bug? It would be really appreciated.

**Comment by nekowinston** [comment]
Does your VPN/proxy/ISP block access to https://cdn.jsdelivr.net/gh/catppuccin/vscode@main/schemas/colorOverrides.schema.json ?

**Comment by Zliced13** [comment]
It turns out Safing Portmaster is blocking it.
![(portmaster-app_v0-2-5)88s4r3_11-19-2023](https://github.com/catppuccin/vscode/assets/101912712/a4698d44-e665-4063-8a83-e6e3c3f31fe1)

**Comment by Zliced13** [comment]
Okay so I added the domain as an exclusion, let's see if that works…
![(portmaster-app_v0-2-5)o7S1W6_11-19-2023](https://github.com/catppuccin/vscode/assets/101912712/42c81d05-fd46-4b40-8ff7-a061d96de08a)

**Comment by nekowinston** [comment]
We're using jsdelivr so it works for more people with ISPs (mainly in India) that regularly temporarily block `raw.githubusercontent.com`, see https://github.com/catppuccin/vscode/issues/197.

**Comment by Zliced13** [comment]
After adding the domain to the list of excluded ones, it now works. Thank you, @nekowinston
![(VSCodium)K1x1r8_11-19-2023](https://github.com/catppuccin/vscode/assets/101912712/6e132986-a7cf-4461-b46f-1198d5d3a21e)

**Comment by Eshanatnight** [comment]
> We're using jsdelivr so it works for more people with ISPs (mainly in India) that regularly temporarily block `raw.githubusercontent.com`, see #197.

@nekowinston Hey, is there an any way to bypass this issue, on Indian ISPs. I understand that this is not an issue with  ***catppuccin***, but I just want some advice. I really don't want to setup a vpn.

Thanks in advance
