### ISSUE TITLE
[BUG] Tab color incorrect when hovering

### ISSUE THREAD

**Issue by iamwxq** [catppuccin/vscode#236]
after updating `catppuccin` pugin to `v3.8.0`, the color comes to incorrect that it displays red but it was light blue before

plugin settings:
 
```json
{
  "catppuccin.accentColor": "blue",
  "catppuccin.boldKeywords": false,
  "catppuccin.bracketMode": "neovim",
  "catppuccin.colorOverrides": {
    "mocha": {
      "base": "#000000",
      "mantle": "#000000",
      "crust": "#000000"
    }
  },
  "catppuccin.extraBordersEnabled": false,
  "catppuccin.italicKeywords": false,
  "catppuccin.italicComments": false,
}
```

screenshot:

<img width="402" alt="Snipaste_2023-12-02_12-25-07" src="https://github.com/catppuccin/vscode/assets/76519998/128f36a1-61f6-4d9b-adf3-cf8806cf0ce3">

**Comment by nekowinston** [comment]
False alarm? 😄

**Comment by iamwxq** [comment]
@nekowinston there is another similar situation that `tab.unfocusedInactiveBackground` also meets the problem

screenshot:

![image](https://github.com/catppuccin/vscode/assets/76519998/897584a9-0cbb-4af2-aebd-52ebf89386c5)

And I think it also due to the `shade()`

**Comment by nekowinston** [comment]
Yeah, I confirmed the bug yesterday, but haven't managed to finish the PR yet, I'll probably do so in a few hours.

**Comment by iamwxq** [comment]
thank you for the hardworking 😊
