### ISSUE TITLE
Color for JSX/Astro/Vue/etc. Components vs HTML elements

### ISSUE THREAD

**Issue by LeonLonsdale** [catppuccin/vscode#248]
Firstly, love the theme.

The only thing missing, for me, is colour differentiation between HTML elements and React components in JSX. In this example we can see that the <main> html element is the same colour as the H!, Suspense, and EventList components.

![code-snapshot](https://github.com/catppuccin/vscode/assets/130412639/12345c0a-813f-4e3d-ba13-fc196df3d8b2)

**Comment by nekowinston** [comment]
Please see https://github.com/catppuccin/vscode/issues/172#issuecomment-1714948598, if you want to change them yourself for JSX/TSX, the token *should be* `support.class.component`.

---

Like #214 I'm unsure if we intend to change other editors too, AFAIK JetBrains also highlights components with `blue` @sgoudham ?

**Comment by LeonLonsdale** [comment]
> Please see [#172 (comment)](https://github.com/catppuccin/vscode/issues/172#issuecomment-1714948598), if you want to change them yourself for JSX/TSX, the token _should be_ `support.class.component`.
> 
> Like #214 I'm unsure if we intend to change other editors too, AFAIK JetBrains also highlights components with `blue` @sgoudham ?

Thanks for getting back so fast. I've taken a look at the linked comments/posts and added the below to the settings.json

```json
"editor.tokenColorCustomizations": {
    "[Catppuccin Mocha]": {
      "textMateRules": [
        {
          "name": "React components",
          "scope": "support.class.component",
          "settings": {
            "foreground": "#dc7070",
            "fontStyle": ""
          }
        }
      ]
    }
  }
```

Attempted as above and also with "support.class.component.react", neither of which appear to work. Have I missed something?

**Comment by nekowinston** [comment]
`meta.tag support.class.component` works.

**Comment by LeonLonsdale** [comment]
> `meta.tag support.class.component` works.

Yep, this works, thanks very much!

**Comment by nekowinston** [comment]
The problem I have with changing the style of the components is that I'm not sure which alternative makes sense with our style guide.

- `blue` - current, same as HTML. I like this look a lot, since I don't really care about the built-in JSX/extended difference. They're both treated the same by the JSX processor, so the same color makes sense IMO.
- `teal` - they'd be the same color as the `</>` brackets surrounding them... Might work?
- `sky` - a brighter blue. Could also work, but probably not that distinctive compared to other non-blue colors.
- `yellow` - You could argue that they're more like a `class`, which should make them yellow according to our style guide, but attributes like `className` are also yellow, which clashes visually.
- `peach` - used for numbers and booleans, visually very distinctive, but I'm not sure if it makes sense from the style guide POV?
- `mauve/red` - keywords & builtins/errors, respectively; I don't think those are a good fit.
- `pink/rosewater` - kind of our go-to *this won't fit anywhere* colors, might also work?
- `green` - strings; would be confusing to use here.

**Comment by LeonLonsdale** [comment]
Yeah for me personally I have some eyesight problems, so if I have to go back into a big tree mix of html/components, it to pass down a new prop, it can be difficult to look at if they're all the same. I would say that since in react they are just functions, then the same as a funcs, but they're blue also. I've opted for this pink colour, which works for me, it's as close as I could get to your pink shades. I'd be happy to use your colour palette rosewater though to keep it on theme (I like the theme a lot) if you have the hex.

![code-snapshot2](https://github.com/catppuccin/vscode/assets/130412639/25a2c8dc-6537-4cb0-bf00-307c5fd2e7da)

**Comment by nekowinston** [comment]
I'll try pink the next time I'm working with a templating language that supports components, I think it'll grow on me.

When it's time to change them I just need to make sure that I switch over all languages which support them at once, so JSX/Astro/Vue/Svelte/Blade...

> I'd be happy to use your colour palette rosewater though to keep it on theme (I like the theme a lot) if you have the hex.

You can find our palette definitions here: https://github.com/catppuccin/catppuccin#-palette

**Comment by LeonLonsdale** [comment]
> I'll try pink the next time I'm working with a templating language that supports components, I think it'll grow on me.
> 
> When it's time to change them I just need to make sure that I switch over all languages which support them at once, so JSX/Astro/Vue/Svelte/Blade...
> 
> > I'd be happy to use your colour palette rosewater though to keep it on theme (I like the theme a lot) if you have the hex.
> 
> You can find our palette definitions here: https://github.com/catppuccin/catppuccin#-palette

Yep, pink works nicely in Mocha!

**Comment by sgoudham** [comment]
> Please see [#172 (comment)](https://github.com/catppuccin/vscode/issues/172#issuecomment-1714948598), if you want to change them yourself for JSX/TSX, the token _should be_ `support.class.component`.
> 
> Like #214 I'm unsure if we intend to change other editors too, AFAIK JetBrains also highlights components with `blue` @sgoudham ?

Hey, yeah JetBrains also highlights these as blue.

I'll try out Pink next time I'm over in Frontend land too, it looks nice from @LeonLonsdale's screenshot!

**Comment by sgoudham** [comment]
I've also had some interest in differentiating `Interfaces` from `Classes` over in JetBrains (currently both yellow) - I wonder if that's applicable to `Types` and `Classes` in Typescript?

**Comment by Stanzilla** [comment]
is there an easy way as a user to reverse this with a snippet? I actually think components should be the same color as html elements so would love to change it back.

**Comment by nekowinston** [comment]
@Stanzilla yes, by overriding the tokens:
```json
  "editor.tokenColorCustomizations": {
    "[Catppuccin Mocha]": {
      "textMateRules": [
        {
          "scope": [
            "support.class.component",
            "support.class.component.jsx",
            "support.class.component.tsx",
            "support.class.component.vue"
          ],
          "settings": {
            "foreground": "#89b4fa"
          }
        }
      ]
    }
  },
```
