### ISSUE TITLE
Add highlight syntax for Regex

### ISSUE THREAD

**Issue by LatenPath** [catppuccin/vscode#255]
Sample regex:
![image](https://github.com/catppuccin/vscode/assets/145383056/fc69b5ee-1a8c-42d2-94e9-fc854ece9402)
`const re = /^(?:\+?(?:\d[\d-. ]+)?\(\s?([2-9]\d{2})\s?\)\s?|[2-9]\d{2}[\s.-]?)?([2-9]\d{2})[\s.-]?(\d{4})$/gm;`

This is a Regex which filter US phone numbers in various formats for sample.

As you can see, many syntax in Regex still not highlight: `group`...etc.

![image](https://github.com/catppuccin/vscode/assets/145383056/fcf11049-09ad-46d6-b143-331b56c3b4db)
`https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions`

Because Regex is popular in many languages, so I think highlight their syntax is a great thing.

Please take note that Regex have many syntax and complex:
![image](https://github.com/catppuccin/vscode/assets/145383056/2c914d2a-865f-4c66-9dc2-bfa3dc6a84d8)

Complex regex sample:
![image](https://github.com/catppuccin/vscode/assets/145383056/b6ef6c74-abb1-4ffe-8bd2-fbecbaf9ad58)
```const re = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/i;```

Anyway, thank you all very much! Love for Catppuccin!

**Comment by nekowinston** [comment]
This one was fun to figure out!
![](https://private-user-images.githubusercontent.com/79978224/294031963-04c4c792-c739-440b-83f6-f6a58c1f8f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTc1MTksIm5iZiI6MTcwNDMxNzIxOSwicGF0aCI6Ii83OTk3ODIyNC8yOTQwMzE5NjMtMDRjNGM3OTItYzczOS00NDBiLTgzZjYtZjZhNThjMWY4ZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIxMjY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmYxODAzOTQ4MmNiMWZkMmZjZThhMzUwNjNkMThhOTE4ZDE3NmEyNTI0YjEyNmVmY2E2N2FlZDgyMzEyYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9Ak4KljaRxSvj4kwUQ0H7cRj2Wo9HHdZ5zMdETWqOo)

Here's the initial implementation, I think a few concepts of our current styleguide translated nicely.
