### ISSUE TITLE
Customization doesn't work on vscode.dev

### ISSUE THREAD

**Issue by Master-Hash** [catppuccin/vscode#261]
## Reproduce

I set

```json
{
    "catppuccin.accentColor": "teal",
}
```
in settings.json.

Expect (installed):
![图片](https://github.com/catppuccin/vscode/assets/56669192/d78792fa-fefa-4ae0-93af-4361f808fdbe)

Real behavior (vscode.dev): 
![图片](https://github.com/catppuccin/vscode/assets/56669192/efd201cd-e28b-4e28-aa50-b53113265625)

**Comment by nekowinston** [comment]
That's sadly a limitation of vscode.dev; Catppuccin should display a notification when changing settings in the Browser version:
https://github.com/catppuccin/vscode/blob/fcf17c881741998ec8085554f35b54a3e0834d2e/packages/catppuccin-vsc/src/browser.ts#L10-L16

We can't save the re-compiled theme back into the extension directory, like we're doing in the App version.
