### ISSUE TITLE
Command center focus state is inverted

### ISSUE THREAD

**Issue by azrdn** [catppuccin/vscode#266]
The default is always focused with the accent color :

![Screenshot 2024-01-05 004819](https://github.com/catppuccin/vscode/assets/95456933/ac6b32db-f560-496c-a4f5-0f7039c8843e)

When focused : 

![image](https://github.com/catppuccin/vscode/assets/95456933/ea595f0e-7e32-4408-b353-69f3af261e66)

Is this intentional or just a bug?

**Comment by nekowinston** [comment]
That... isn't intentional. I forgot VSCode had this feature tbh.
