### ISSUE TITLE
change from mkDerivation to vscode-utils.buildVscodeExtension caused missing version attribute

### ISSUE THREAD

**Issue by pixL404** [catppuccin/vscode#280]
The commit 3cc3258 broke the extension on nixOS.

I think this is due to the change from `pkgs.stdenvNoCC.mkDerivation` to `pkgs.vscode-utils.buildVscodeExtension` in the default.nix.

According to [this](https://github.com/NixOS/nixpkgs/blob/b7d435df6455b17c1a06bbdbd66dee0154746f95/pkgs/applications/editors/vscode/extensions/vscode-utils.nix#L104) the attribute `version` should be set by the extension.

In the default.nix the version number is used, but not inside the build attribute set.

This is my stacktrace when trying to rebuild with the newest flake input:
```shell
error:
  … while calling the 'head' builtin

    at /nix/store/xxx-source/lib/attrsets.nix:960:11:

    959|         || pred here (elemAt values 1) (head values) then
    960|           head values
       |           ^
    961|         else

  … while evaluating the attribute 'value'

    at /nix/store/xxx-source/lib/modules.nix:809:9:

    808|     in warnDeprecation opt //
    809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
       |         ^
    810|         inherit (res.defsFinal') highestPrio;

  (stack trace truncated; use '--show-trace' to show the full trace)

  error: attribute 'version' missing

  at /nix/store/xxx-source/pkgs/applications/editors/vscode/extensions/vscode-utils.nix:110:15:

    109|
    110|     version = ext.version;
       |               ^
    111|
```

**Comment by nekowinston** [comment]
Are you overwriting the `nixpkgs` input? The CI run passed successfully https://github.com/catppuccin/vscode/actions/runs/7425104839 🤔

**Comment by nekowinston** [comment]
Oh interesting - it doesn't fail on the build, but on building the VSCode environment with home-manager.
As you suggested, it's happening because the `version` is missing; I assume that this is a standard that Home-Manager expects, but isn't enforced in the builder.

I will update the derivation accordingly, thanks for diving in!

**Comment by pixL404** [comment]
Thank you for the fix - everything is working as expected!
