### ISSUE TITLE
What is the name of the font used in the VS Code screenshot?

### ISSUE THREAD

**Issue by LaxVox** [catppuccin/vscode#29]
I'm not sure if this question belongs here, but I didn't find any other way to ask and I would like to use that font in my VS Code setup.

**Comment by MatthiasPortzel** [comment]
Looks like [JetBrains Mono](https://www.jetbrains.com/lp/mono/). The ligatures give it away.

**Comment by LaxVox** [comment]
Looks like you're right. Thank you!
