### ISSUE TITLE
Question: Which font is used on preview screenshots?

### ISSUE THREAD

**Issue by Mibeon** [catppuccin/vscode#293]
Hey guys,

does anyone know which monospaced font is used on preview screens of this theme? Looks amazing. I couldn't find similar fonts on the web. Maybe I searched not long enough.

https://raw.githubusercontent.com/catppuccin/vscode/cf7019fdeba269650940fb0bd2c4e50c7bf498d8/assets/preview.webp

![font](https://github.com/catppuccin/vscode/assets/35590178/b8e8de39-332e-4e77-abff-592de0734099)

**Comment by nekowinston** [comment]
[Berkeley Mono](https://berkeleygraphics.com/typefaces/berkeley-mono/) by Berkeley Graphics.
