### ISSUE TITLE
Python docstring is too bright 

### ISSUE THREAD

**Issue by luong-komorebi** [catppuccin/vscode#30]
Thank you for pushing this for vscode. 

I want to report a problem  that python docstring is probably too bright:

![image](https://user-images.githubusercontent.com/15828926/180174954-d0f39c64-c31c-4d44-9efe-473742b63eda.png)
![image](https://user-images.githubusercontent.com/15828926/180175178-86c63c17-9722-4f35-b4e2-883e7d2d71fb.png)

as compared to what I had on neovim 

![image](https://user-images.githubusercontent.com/15828926/180175034-2b816f26-c15b-4e16-b4e9-6e76282bb869.png)
![image](https://user-images.githubusercontent.com/15828926/180175144-780e3411-7006-4b9c-95aa-7cc9e8855134.png)

**Comment by otzslayer** [comment]
It might not be a good way to resolve this issue, but you can use the r-string. ;)

**Comment by nekowinston** [comment]
This should be fixed with the update to 0.2.0, 287785ab92c5c235dae76b93f877243b579e0828, Python docstrings look like this now:
![CleanShot 2022-08-09 at 11 54 51](https://user-images.githubusercontent.com/79978224/183620379-5f741e6b-c6ed-45f2-ad69-9a1e4530d4a0.png)
