### ISSUE TITLE
Improve highlight contrast in setting's inputs

### ISSUE THREAD

**Issue by fxsalazar** [catppuccin/vscode#326]
Here it's almosst impossible to see which word is highlighted/selected: 

![Screenshot 2024-02-17 at 23 22 14](https://github.com/catppuccin/vscode/assets/2998771/5c801521-be5f-4911-8053-d982f61e441a)

Spoiler: is `JetBrainsMono`

**Comment by code-IM-perfect** [comment]
similar issue with highlighted keyword and selected part of it-
![image](https://github.com/catppuccin/vscode/assets/77197959/4bce83c5-8c43-4c09-85c5-10d70aedf74b)
I think the selected part should be a little brighter to be clearly visible without this much zoom
