### ISSUE TITLE
Syntax highlighting error in ABAP code

### ISSUE THREAD

**Issue by Shekhar0050M** [catppuccin/vscode#327]
I am unable to recognize the error.
<img width="960" alt="Screenshot 2024-02-22 154135" src="https://github.com/catppuccin/vscode/assets/62455266/85115392-387a-4136-afd6-8c5019e2c577">

**Comment by nekowinston** [comment]
Hi there, could you please link to that code snippet so I can have a look at it myself?
Also since I'm not familiar with ABAP, are you using https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abap for highlights?

**Comment by Shekhar0050M** [comment]
Sure, here it is https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/index.htm

**Comment by nekowinston** [comment]
There is nothing I can do about this, the parser for ABAP just seems to be pretty poor, sorry.
Everything that shows up as green gets interpreted as `string.interpolated.abap` when I'm using `larshp.vscode-abap`, I don't know which extension you're using, but that one seemingly has similar problems.
