### ISSUE TITLE
Improve highlighting of selected subpart of a keyword

### ISSUE THREAD

**Issue by code-IM-perfect** [catppuccin/vscode#331]
The color of keyword highlight and the highlight of the actual selection are almost impossible to distinguish.
![Screenshot_20240303_194224](https://github.com/catppuccin/vscode/assets/77197959/24365248-5930-48e5-aaad-21ce24760610)
Gets worse on normal zoom.
![Screenshot_20240303_194131](https://github.com/catppuccin/vscode/assets/77197959/67979003-aa35-4a83-be96-1184f4f184a8)

I think a solution similar to #330, where the theme color was used for the actual selection would be appropriate.

**Comment by nekowinston** [comment]
Closed via #342, the accent color lead to extremely unreadable selections for some (most) accent colors.
