### ISSUE TITLE
Select flavor when installing from the marketplace

### ISSUE THREAD

**Issue by numpad** [catppuccin/vscode#34]
Installing the Catppuccin color theme from one of the preferred installation methods does not provide me with an option to switch to "Latte" or other flavors.

I am using Visual Studio Code 1.70.0.

**Comment by yosiat** [comment]
@numpad the new version isn't released yet to market, suggest to follow this issue (like I do) - https://github.com/catppuccin/vscode/issues/32

**Comment by numpad** [comment]
That makes sense, thanks!

**Comment by nekowinston** [comment]
Closing this as a duplicate of #32
