### ISSUE TITLE
[REQUEST] Adding more color differentiation for Luau language

### ISSUE THREAD

**Issue by jo-project** [catppuccin/vscode#346]

**Comment by nekowinston** [comment]
Looks fine to me when using https://marketplace.visualstudio.com/items?itemName=Nightrains.robloxlsp, which seems to be the most popular Luau LSP/Highlight extension:
![2024-03-13-105846@2x](https://github.com/catppuccin/vscode/assets/79978224/594ec92a-5115-43dd-9873-2952759868b1)

**Comment by 0xJWLabs** [comment]
Can you also try it with luau lsp?

**Comment by nekowinston** [comment]
Seems that one is even less maintained, idk enough about the luau ecosystem, the official one seems fine to me from a pure highlighting perspective.
