### ISSUE TITLE
open-vsx.org package 

### ISSUE THREAD

**Issue by adamszegedi** [catppuccin/vscode#35]
Hi, 

First of all i really like this theme. :heart_eyes:  

I noticed you updated the theme inside the vscode marketplace, but unfortunatelly non microsoft releases of vscode like gitpod, vscodium, code - oss, cannot use microsoft marketplace they use the openvsx equivalent of it, which is still at the 1.0.6.
https://open-vsx.org/extension/Catppuccin/catppuccin-vsc

Would it be possible to extend the release script and not just release to the microsoft store but the open-vsx store aswell?

**Comment by nekowinston** [comment]
I'll try to get control of the namespace & the update published.

**Comment by nekowinston** [comment]
It should be updated now 🚀 

https://open-vsx.org/extension/Catppuccin/catppuccin-vsc
