### ISSUE TITLE
Investigate improvement of Haskell syntax highlighting

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/vscode#360]
From the Discord.

Test the syntax hl with https://github.com/JustusAdam/language-haskell / https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell
More random Haskell code: https://rosettacode.org/wiki/Category:Haskell

**Comment by nekowinston** [comment]
Honestly couldn't find many places where there would be obvious improvements, but I'm also not far into my Haskell journey yet. Closing this, as I won't continue work on this.

**Comment by DavSanchez** [comment]
Hey! Sorry for posting on a closed issue, but I was just searching for any effort in Haskell improvements with these awesome themes and stumbled upon this one.

I'm not sure if the Catppuccin themes could be configured to solve this issue away, but one area of improvement could be the colouring of data constructors. Take as example the last line shown in this function, both in Cappuccin Mocha:

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/37eb8c0f-32db-4e7d-bd88-515c225aca98" />

and Lambda Dark+ (from the [Lambda Black](https://marketplace.visualstudio.com/items?itemName=janw4ld.lambda-black) extension):

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/7bd5fe80-5540-468b-a976-77bc32492f80" />

This Lambda Black themes were made with Haskell specifically in mind (among others in the FP space like Nix), so not sure if following the approaches from that extension could compromise existing design decisions for Catppuccin.

**Comment by nekowinston** [comment]
Pinging @backwardspy so that they can see your comment. I've stopped maintaining this theme (but funnily enough picked up Haskell as one of my go-to programming languages since).

The missing highlight for the `SuggestedMatch` Type is probably just a result of missing Semantic (LSP-aware) highlights, as HLS is making heaving use of these.
