### ISSUE TITLE
Error squiggly lines are too close to the word

### ISSUE THREAD

**Issue by shafiqimtiaz** [catppuccin/vscode#361]
While using Catpuccin-mocha, the error squiggly lines are too close to the word, to the point, its very difficult to pinpoint.

`Bug details as below:`

Getting This
![image](https://github.com/catppuccin/vscode/assets/57990344/733c2ae6-cdf8-46d6-a524-517923c93ecf)

Expected This
![image](https://github.com/catppuccin/vscode/assets/57990344/37f7f3c0-237b-4f94-86cc-806aa3a49b11)

**Comment by lluchkaa** [comment]
Same here, also noticed it after 1.88 release

**Comment by palashmon** [comment]
This issue is also reported after the recent VS Code version: Code 1.88.0 update:
- https://github.com/microsoft/vscode/issues/209614

**Comment by CharlesAttend** [comment]
I would like to mention here the temporary solution you've explained [here](https://github.com/wesbos/cobalt2-vscode/issues/248#issuecomment-2042204084). Thank you @palashmon!

> This issue is also reported after the recent VS Code version: Code 1.88.0 update:
> 
> * [Squiggly lines have moved slightly upwards after the update microsoft/vscode#209614](https://github.com/microsoft/vscode/issues/209614)
> 
> Please consider giving this VS Code issue a like and leaving a comment there, so that it could be given higher priority for the upcoming release.
> 
> ### Temporary Solution
> Use less vibrant color or any other color you may like for the underline:
> 
> ```json
> "workbench.colorCustomizations": {
>   "[Cobalt2]": {
>     "editorError.foreground": "#ff000088",
>     "editorWarning.foreground": "#ffe60033",
>     "editorInfo.foreground": "#00ff0088"	
>   }
> }
> ```
> 
> Or, disable the zigzag lines and use a background color instead:
> ### Optional
> Use `Error Lens` vscode extension:
> 
> * https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

**Comment by palashmon** [comment]
@CharlesAttend Glad it helped!

**Comment by nekowinston** [comment]
Seems this got fixed upstream and will be fixed in the May release, or latest Insiders version.
