### ISSUE TITLE
When I'm writing a Vue project in VSCode, the colors of strings and object properties are the same, which makes it a bit hard to read.

### ISSUE THREAD

**Issue by yuguaa** [catppuccin/vscode#382]
one dark pro & catppuccin frappe
![image](https://github.com/catppuccin/vscode/assets/58333667/4fc5c181-5c3d-4713-868b-86fb57323749)

**Comment by nekowinston** [comment]
I can't replicate this, are you using the [`Vue - Official`](https://marketplace.visualstudio.com/items?itemName=Vue.volar) extension?

![2024-04-25-100102@2x](https://github.com/catppuccin/vscode/assets/79978224/f08924eb-56d4-46df-8760-85772081aee3)

If you're using the official extension, please hover over a key, and use the *Command Palette* -> *Developer: Inspect Editor Tokens and Scopes*, and share a screenshot like this. Linking to example code also always helps.

**Comment by yuguaa** [comment]
The above images are all based on Vue 2 projects using Vue CLI. However, the same issue exists even when using the Options API with Vite and Vue 3.
![image](https://github.com/catppuccin/vscode/assets/58333667/e36eb1bc-ccc0-4073-8ec1-00b22239dea7)

**Comment by yuguaa** [comment]
> The top-most `string.unquoted.js` is wrong, and I can't replicate it, even when I'm using a minimal vscode.dev instance, with just Volar & Catppuccin installed, with a repository of yours:最 `string.unquoted.js` 上面的是错误的，我无法复制它，即使我使用最小的 vscode.dev 实例，只安装了Volar和Catppuccin，并带有您的存储库： ![2024-04-25-103903@2x](https://private-user-images.githubusercontent.com/79978224/325536279-5f1a63d0-614c-4daf-b1cc-47a9f0774ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzQ4NTQsIm5iZiI6MTcxNDAzNDU1NCwicGF0aCI6Ii83OTk3ODIyNC8zMjU1MzYyNzktNWYxYTYzZDAtNjE0Yy00ZGFmLWIxY2MtNDdhOWYwNzc0ZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA4NDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDZlODAzNjQwYjUwN2JjYjY4MTc5ZjM4YzVmZGJiYjk4MDk1NTNkNDEwZjQzYzkzYjFkYmE4ZGU3NTFlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F1aY28EXMNMlFHCEJHrruSrz50Q97u8KWLxdw5ONxEk)

Strange question, maybe I need to reinstall VS Code and try again.

**Comment by nekowinston** [comment]
Good luck solving the issue, and please feel free to open an issue if it persists, and you manage to create a reproducible minimal config.
