### ISSUE TITLE
Unchecked, unfocused check boxes are invisible (when view a merge conflict)

### ISSUE THREAD

**Issue by MatthiasPortzel** [catppuccin/vscode#39]
Viewing a merge conflict from VS Code's git integration. The editor puts a check box in the gutter next to each change so that you can choose the left or right resolution. For example, there's one on line 15 below. Once it's focused it gets a blue outline, and clicking it causes it to become checked, obviously, but it's invisible at first.

<img width="83" alt="image" src="https://user-images.githubusercontent.com/19734415/187262896-623ee1f4-41e2-4c67-969a-89ff4e6fe5f1.png">

**Comment by nekowinston** [comment]
Thanks for raising this issue, I'll get it fixed with the next release!
I'm currently working on #38, I should get it done within the next few days.
I'll update when it's either released or included in the pre-release. 👍
