### ISSUE TITLE
Godot scene `.tscn` icon not working in light mode

### ISSUE THREAD

**Issue by benediktms** [catppuccin/vscode#398]
When working with the editor in dark mode the icons work properly as seen below:

![Screenshot 2024-06-05 at 09 49 28](https://github.com/catppuccin/vscode/assets/48836135/e78874d9-8d90-4e4d-be8f-71eae0d15b67)

However when switching to light mode the icons get replaced with this:

![Screenshot 2024-06-05 at 09 51 16](https://github.com/catppuccin/vscode/assets/48836135/fe6a2b90-f56c-448c-9daa-846abd32b625)

I tested this with different color themes, the result is the same. I'm on macOS, I can test this on windows and linux later if needed.

**Comment by backwardspy** [comment]
i'm not currently able to replicate this.

i notice your other icons are not switching to latte either, do you have `catppuccin.syncWithIconPack` enabled? i don't know if it's related, but let me know if that changes anything.

![image](https://github.com/catppuccin/vscode/assets/289746/aeff7444-f64c-4388-961a-fe20897bcf76)
![image](https://github.com/catppuccin/vscode/assets/289746/d4926fb3-73e5-4bde-bb52-5c620cd464fe)

**Comment by benediktms** [comment]
@backwardspy thanks for getting back to me! I did have that setting enabled, but it doesn't seem to work for me. Toggling the themes doesn't change the icon theme. I tried to reset both the theme plugin and the icon plugin, but it doesn't seem to work. Also setting the icon theme manually to Latte will still display those broken icons

**Comment by benediktms** [comment]
Actually I got the icon sync to work after completely uninstalling the plugins and restarting VSCode and installing plugins again. But the godot icons are still broken

**Comment by benediktms** [comment]
I think I found the reason why the icon toggle does not work for me:

I sync my VSCode theme to the system theme, so if I have a dark system theme I use Macchiato, if I have a light theme I use Latte. The problem is that VSCode does not actually change the current theme. 

![Screenshot 2024-06-05 at 12 05 39](https://github.com/catppuccin/vscode/assets/48836135/2e4b0525-81d1-40aa-9bc7-fe43dab79abf)

![Screenshot 2024-06-05 at 12 06 14](https://github.com/catppuccin/vscode/assets/48836135/b0d2a6a1-c829-4818-80c0-ea9df7283113)

From what I can tell the plugin looks at the `workbench.colorTheme` and not the `preferredLightColorTheme` and `preferredDarkColorTheme` settings, probably, maybe it's not easy to tell what mode `window.autoDetectColorScheme` is currently in?

Either way for me the Latte icons are still broken

**Comment by backwardspy** [comment]
thanks for that additional info, that's really helpful. i'll look into this shortly and get back to you.

**Comment by backwardspy** [comment]
> Either way for me the Latte icons are still broken

if even manually setting the icon theme to latte doesn't resolve this, please could you raise an issue for it on https://github.com/catppuccin/vscode-icons? i don't think that part of the problem is caused by this plugin.
