### ISSUE TITLE
Red background on the active line

### ISSUE THREAD

**Issue by guilhermedeandrade** [catppuccin/vscode#40]
Just installed the theme and I'm using the Latte variant. I don't know why but the active line always have a red background. Is it the expected behavior?

<img width="485" alt="image" src="https://user-images.githubusercontent.com/8797405/189536983-07409db5-89eb-4dd9-8fc0-3d94f56f1d5b.png">

**Comment by sgoudham** [comment]
Hey! Thanks for reporting this issue. 
We're currently in the process of updating the VsCode port to avoid highlights like this. 

For this issue itself, I believe it's only in the pre-release version, could you please use the non pre-release version for now? Thanks!

**Comment by guilhermedeandrade** [comment]
Yes, I'm using the the VSCode - Insiders indeed.

Thanks for the fast reply!
