### ISSUE TITLE
Unable to uninstall extension from Azure Data Studio

### ISSUE THREAD

**Issue by FrostyProgrammer** [catppuccin/vscode#401]
MBP M1, Azure data studio, all updated. I've tried many times to uninstall and even manually looked for references and files to remove. When I try the uninstall option it appears to be working but then after it is still there.

**Comment by sgoudham** [comment]
Hey :wave:,

I'm unfamiliar with the installation/uninstall process for Azure Data Studio, could you please let me know how you installed the extension (i.e. through the VSCode marketplace / built-in extension pane?) and how did you try to uninstall it? (i.e. pressing uninstall in a built-in extension pane?)

Apologies if these are basic questions!

**Comment by sgoudham** [comment]
Closing as stale/not-planned due to inactive author.
Feel free to re-open!

**Comment by FrostyProgrammer** [comment]
Hello!

It was a while ago so I'm not certain on the install, I believe it was installed using the menu option of 'Install Extension from VSIX Package'.

It shows in my Extensions pane and I can click to uninstall, then proceed to 'Reload', but then it is still there
￼

I would like this to work however I have customized it now and no longer plan to uninstall.

Thanks
