### ISSUE TITLE
Set `editor.wordHighlightStrongBackground`?

### ISSUE THREAD

**Issue by prurph** [catppuccin/vscode#429]
It seems like catppuccin does not set `--vscode-editor-wordHighlightStrongBackground` (found [here](https://github.com/catppuccin/vscode/blob/2d7388ffe7321f588b2f54e2ffaab9fb7c9dde14/packages/catppuccin-vsc-typegen/types/workbench-colors.d.ts#L643) in the type). This results in use of the default that doesn't match the theme (note the teal background on the function `user` parameter):

![CleanShot 2024-08-20 at 18 44 21@2x](https://github.com/user-attachments/assets/10bb3b8e-1c80-436b-b298-af178cc0c329)

Would it be possible/desirable for the theme to set this color? Out of the box, it is a different color than the regular selection background, however the catppuccin spec doesn't speak to different selection backgrounds based on context, so it's not clear to me whether the appropriate course would be to make it the same as `editor.wordHighlightBackground` or attempt to differentiate it as VSCode normally does.

**Comment by sgoudham** [comment]
Hey 👋,
Thanks for raising the issue.

Personally, I'm not such a fan of it. I've got some screenshots below where the first two are the same colour as `editor.wordHighlightBackground` and the last two are trying to make it stand out a tiny bit. I'm curious which one you'd prefer. 

`Mocha - opacity(palette.overlay2, 0.2)`
![image](https://github.com/user-attachments/assets/6aeb4e91-64cd-4db6-a2a2-e96dc3ceff57)

`Latte - opacity(palette.overlay2, 0.2)`
![image](https://github.com/user-attachments/assets/3295afe0-f8da-44da-882d-383e865a1122)

`Mocha - opacity(palette.blue, 0.2)`
![image](https://github.com/user-attachments/assets/195db702-87fe-4af9-bf63-f0dd2516513e)

`Latte - opacity(palette.blue, 0.1)`
![image](https://github.com/user-attachments/assets/d4791722-31c7-4932-ad19-1f35dc1cd808)

**Comment by prurph** [comment]
Thanks for responding! To my eyes both sets of screenshots look good!; because the differentiation in the second pair is so subtle I think either would look good.

My main gripe in raising the issue is that by not setting the variable to something theme appropriate we get that teal-blue background that is the VSCode default and that definitely clashes with the Catppuccin theme IMO.

Either of these adjustments would fix that and give a consistent visual style, so I'd be delighted with either.

**Comment by sgoudham** [comment]
Thanks for the swift reply! (Apologies on my part for how long it's taken me to reply to this one haha) 

I've gone with the light shade of blue since I received some feedback on our discord that keeping the colour differentation is good.

It'll be included in the next release!
