### ISSUE TITLE
file modified tab color on latte theme is difficult to make out

### ISSUE THREAD

**Issue by jpike88** [catppuccin/vscode#437]
<img width="544" alt="Screenshot 2024-09-23 at 10 23 31 AM" src="https://github.com/user-attachments/assets/eb1f28f0-1931-45ad-8685-9619de23474f">

**Comment by sgoudham** [comment]
Hey 👋,

The theme, by default, uses `crust` for the tab bar which results in a much nicer contrast:

![image](https://github.com/user-attachments/assets/7029f662-2e2c-4c99-b416-685303c7ca58)

I'd highly suggest you choose a less harsh colour to contrast against the top bar. I'll be closing this issue as not planned, hope that's okay!
