### ISSUE TITLE
Make currently opened file more distinguishable

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/vscode#44]
The colour for the currently selected tab/file is the same as for the tab and top bar background. Inavtive tabs/files are darker and thus much more prominent in terms of visual hiarchy. I'd suggest to either switch the colours around, or use one of the overlay colours to indicate the currently selected tab/file. c:

![Current File Selection](https://user-images.githubusercontent.com/35840154/194552545-067ad878-a113-4352-b21f-5be78edf62bf.png)

**Comment by auchynnikau** [comment]
Could you assign this issue on me? I'll try to experiment and find a better approach.

**Comment by andreasgrafen** [comment]
Done. c:
I'm looking forward to see some suggestion. I've locally edited the theme to just switch the active and inactive tab colours, which works better, but it still isn't perfect.

**Comment by auchynnikau** [comment]
Highlighting active tab with border looks pretty well:

![image](https://user-images.githubusercontent.com/33329898/196284712-69691e21-c30e-4b5c-8aba-eb1f6d159b5a.png)

Fits line number color
![image](https://user-images.githubusercontent.com/33329898/196285953-0f084676-64c6-4dca-99c1-7e9e092ae57a.png)

Fits active line number color
![image](https://user-images.githubusercontent.com/33329898/196279170-248ac8b8-ff63-4b04-88ba-c29ae9658744.png)

![image](https://user-images.githubusercontent.com/33329898/196287643-8d8eafd0-755e-459c-a48e-29d0d30b8a97.png)
![image](https://user-images.githubusercontent.com/33329898/196279055-48449895-adce-4164-9998-ecc3966cca3b.png)
![image](https://user-images.githubusercontent.com/33329898/196279097-dd2335e6-285f-45b3-a997-1ad2430f07b1.png)

Border bottom:
![image](https://user-images.githubusercontent.com/33329898/196284821-19e70f94-525f-4526-a256-5a5cbcab0506.png)
![image](https://user-images.githubusercontent.com/33329898/196289527-7004f350-fe84-45c6-ba6c-c8cf70564cff.png)
![image](https://user-images.githubusercontent.com/33329898/196289370-ff380dd4-c91d-4817-9fb7-724498f86000.png)
![image](https://user-images.githubusercontent.com/33329898/196287923-3f4fc83b-a5c8-4e83-802b-344910d0cb54.png)
![image](https://user-images.githubusercontent.com/33329898/196286245-12c09081-c42b-4be3-8271-2b5485bfdac4.png)
![image](https://user-images.githubusercontent.com/33329898/196289432-4cfc4819-57a3-48e7-be56-fdf6228605f8.png)


Another approach is to use the same styling of active list items (darker/lighter):
![image](https://user-images.githubusercontent.com/33329898/196287358-a8f72178-6727-43aa-86b8-c15ca89ff65c.png)
![image](https://user-images.githubusercontent.com/33329898/196290221-73be0b20-dd02-4a55-bec9-3ede17bb8ce8.png)

![image](https://user-images.githubusercontent.com/33329898/196288757-5f0f3fd1-acd0-497c-aa5b-cbb79f2906f6.png)

What do u think?

**Comment by sgoudham** [comment]
This is pretty great work, thank you!

The updated JetBrains port will have this highlight here for the current file:
![image](https://user-images.githubusercontent.com/58985301/197292008-cd540c8e-9887-4c00-940e-bb2ea7ef147f.png)

I think it would make sense to keep it as consistent as possible. With the pink underline and if possible, the pink file name. What do you think? @auchynnikau

**Comment by auchynnikau** [comment]
> This is pretty great work, thank you!
> 
> The updated JetBrains port will have this highlight here for the current file: ![image](https://user-images.githubusercontent.com/58985301/197292008-cd540c8e-9887-4c00-940e-bb2ea7ef147f.png)
> 
> I think it would make sense to keep it as consistent as possible. With the pink underline and if possible, the pink file name. What do you think? @auchynnikau

I'm agree with you and I can prepare PR for it. This color will be applied for all themes?

**Comment by auchynnikau** [comment]
@andreasgrafen now we can close this issue
