### ISSUE TITLE
`settings.json` automatically opens when operating system changes theme

### ISSUE THREAD

**Issue by Saafo** [catppuccin/vscode#440]
I'm using auto enabled dark mode in system, and also in Vscode for years(at least 2 years).
I've found that recently(at least 2 months), sometimes when dark mode switched in Vscode, `settings.json` file will auto open with change to `iconTheme`(e.g., change `catppuccin-latte` to `catppuccin-macchiato`) without saving this file nor closing.
I'm not sure whether others will met this issue, nor it is a bug of Vscode or catppuccin extension.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/e6f3266d-865c-42f3-9109-ea10431035eb">

**Comment by sgoudham** [comment]
Hey 👋,

I'm not sure if I correctly understand the issue but I believe you're saying that when you switch the operating system theme while VSCode is open on a different file, it sometimes automatically opens the `settings.json` file with a change to the `workbench.iconTheme` key? Feel free to correct me if I'm wrong!

I've set the following options in my configuration to try and reproduce this issue:

```json
"catppuccin.syncWithIconPack": true,
"window.autoDetectColorScheme": true,
"workbench.iconTheme": "catppuccin-mocha",
"workbench.preferredLightColorTheme": "Catppuccin Latte",
"workbench.preferredDarkColorTheme": "Catppuccin Mocha",
```

However, as shown in the screen recording below, I'm unable to reproduce this issue:

https://github.com/user-attachments/assets/3e384e71-505e-49a4-b191-21542e496b78

I'll keep this issue open for now, but unless I've misunderstood the issue, I currently cannot reproduce this bug.

**Comment by Saafo** [comment]
Hi @sgoudham thanks for reproduction! I found that this bug disappeared recently, we can close this issue!
