### ISSUE TITLE
Weird color change since visual studio code v1.95 and nvidia driver 565

### ISSUE THREAD

**Issue by maxawake** [catppuccin/vscode#451]
![image](https://github.com/user-attachments/assets/14295ca2-553a-4879-9d07-746174798d89)

I am on Arch Linux with Kernel 6.11.6 using a NVIDIA 4070ti with the 565 drivers on Wayland with Gnome 47. I recently updated vscode to 1.95. Now it seems that the catpuccin theme is broken. Its very weird and i am not sure if you are the right persons to ask this. But maybe you can hint me where to look for the reason of this bug. Thanks in advance!

**Comment by sgoudham** [comment]
Hey :wave:,

I have absolutely no idea how that is happening but the theme is still working :thinking: 

![image](https://github.com/user-attachments/assets/129601ba-5f56-42af-a9b5-7f04557e7307)

Have you tried uninstalling and reinstalling the theme?

**Comment by maxawake** [comment]
Hey thanks for the prompt answer!

Yes sure, i tried reinstalling it. I came to the conclusion that is must be a Wayland/Nvidia/Electron issue, since it also applies to other themes and other electron apps (e.g. obsidian) but everything is still fine if i switch back to X11...

**Comment by sgoudham** [comment]
Oh wow yeah definitely not a Catppuccin issue then. I don't use Wayland so I'm not in a position to offer any help, sorry!

I'll close this issue since it's not related to Catppuccin but I hope you find a solution to your problem!

**Comment by backwardspy** [comment]
@maxawake i have no idea how to fix this or why it'd even be this way, but i notice the colours in your screenshot are all BGR instead of RGB, for example the background which is usually #1e1e2e for catppuccin is instead #2e1e1e.

maybe poke around in your graphics settings to see if there's a colour format option that you can change from BGR to RGB.
