### ISSUE TITLE
Bad UI in the code view popup

### ISSUE THREAD

**Issue by Kush-Dhingra** [catppuccin/vscode#457]
![image](https://github.com/user-attachments/assets/2a3ba75f-32d3-4a40-bf3b-b8395cbb7f28)
As you can see above, the popup bg does not match with the catpuccin theme and Suggestion: Add some border radius to the popup

**Comment by 42Willow** [comment]
The popup background is mocha mantle which is actually correct I think (see [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md))

using surface0 or similar on this popup would not offer as much contrast between the background and the accent colours (blue and yellow)

As for the border radius around the popup: I think this theme aims to just provide the colours over the default UI, but you can apply your own css modifications on top of it if you prefer a more rounded popup

catppuccin
![image](https://github.com/user-attachments/assets/87793f6b-aacb-4b9c-be8d-83648fa18d1c)
default dark
![image](https://github.com/user-attachments/assets/532fed5d-40c8-4aac-b2c9-b0e7cd663453)
