### ISSUE TITLE
script shebang shows as not catppuccin color

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/vscode#46]
<img width="134" alt="image" src="https://user-images.githubusercontent.com/72631767/195708211-7d29c55c-aebb-4dc9-a25a-7b84cbef29f9.png">
the css styling of this is:

```css
.monaco-editor .ced-2-TextEditorDecorationType21-1 {
    color: rgb(255, 45, 0) !important;
}```

**Comment by andreasgrafen** [comment]
Mh, can't relate. shebangs look fine for me. o:
Is your theme updated to the latest version?

![sh](https://user-images.githubusercontent.com/35840154/195708636-5d7e317d-99b9-4770-bc12-36a37242805c.png) ![bash](https://user-images.githubusercontent.com/35840154/195708664-e2332f83-96d9-4cb2-ac33-d08f0146e8a9.png) ![env fish](https://user-images.githubusercontent.com/35840154/195708872-b609249e-6467-4773-9219-7077cc7e6f92.png)

**Comment by BlueFalconHD** [comment]
> Mh, can't relate. shebangs look fine for me. o: Is your theme updated to the latest version?
> 
> ![sh](https://user-images.githubusercontent.com/35840154/195708636-5d7e317d-99b9-4770-bc12-36a37242805c.png) ![bash](https://user-images.githubusercontent.com/35840154/195708664-e2332f83-96d9-4cb2-ac33-d08f0146e8a9.png) ![env fish](https://user-images.githubusercontent.com/35840154/195708872-b609249e-6467-4773-9219-7077cc7e6f92.png)

i just uninstalled and reinstalled+reloaded. still happening. perhaps it is a plugin but the style should work either way.

**Comment by BlueFalconHD** [comment]
also my plugins
<img width="787" alt="image" src="https://user-images.githubusercontent.com/72631767/195710176-18f2271d-eeb8-40b5-bdec-321bfd2ef0c1.png">

**Comment by sgoudham** [comment]
It looks like the shebang looks fine with the theme. Is this issue okay to be closed? @BlueFalconHD

**Comment by BlueFalconHD** [comment]
> It looks like the shebang looks fine with the theme. Is this issue okay to be closed? @BlueFalconHD
> Unless you can provide some reproducible config/steps

Its fine. I was using VSCode for a functioning Fish LSP and just wanted to point that out?
