### ISSUE TITLE
Whitespace characters are hardly distinguishable

### ISSUE THREAD

**Issue by auchynnikau** [catppuccin/vscode#47]
## Steps to Reproduce:
Reproduces after enabling `Editor: Render Whitespace` in VS Code settings.

## Expected Behaviour:
Whitespaces are distinguishable like in default VS Code theme.

<img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196683513-e68b8ec0-8000-4506-93a1-73b2d0b2c63a.png"><img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196683545-65224b66-e6c6-4143-86ed-453d187bc06d.png">

## Current Behaviour:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196682889-7bc5f4a3-a9a7-4ecb-a167-0f607983de79.png"><img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196682930-08d86ddf-8904-477b-998c-73d89bcafa91.png">

## Possible Implementation:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196687979-2125dff8-e358-4703-8660-2c4bb4189a55.png"><img width="142" alt="image" src="https://user-images.githubusercontent.com/33329898/196688855-d9b6f610-7486-453a-a5bf-33b1d5e3bf56.png">

These colors are draft version, but it represents the main idea. If this issue is relevant, you can assign it on me, I'm ready to help with it.

**Comment by sgoudham** [comment]
Hey! Thanks for bringing this to our attention. It would be great if you could improve this!

There's actually a current draft PR and branch focused on improving the highlights and extending customizability! It would be great if you could implement your possible implementation against the [dev](https://github.com/catppuccin/vscode/blob/dev/src/theme/index.ts#L2512) branch.

Feel free to join our [discord](https://discord.com/invite/r6Mdz5dpFc) if you have any further questions

**Comment by auchynnikau** [comment]
> Hey! Thanks for bringing this to our attention. It would be great if you could improve this!
> 
> There's actually a current draft PR and branch focused on improving the highlights and extending customizability! It would be great if you could implement your possible implementation against the [dev](https://github.com/catppuccin/vscode/blob/dev/src/theme/index.ts#L2512) branch.
> 
> In terms of the highlights themselves, I think it makes sense to increase the value in the opacity field as it's currently too dark
> 
> Feel free to join our [discord](https://discord.com/invite/r6Mdz5dpFc) if you have any further questions

Unfortunately increasing the value in the opacity field don't affect this issue, so I've updated foreground values for each theme.

**Comment by auchynnikau** [comment]
@sgoudham now we can close this issue
