### ISSUE TITLE
No setting called "import theme"

### ISSUE THREAD

**Issue by ZenithDS** [catppuccin/vscode#5]
Hey I'm not sure if this is something specific to vscodium but I don't see an option called "import theme" anywhere in the setting even after searching

**Comment by morphisjustfun** [comment]
It seems like you have to clone the repo and then copy the folder to .vscode/extensions. Reload vscode and you are done. 💯

**Comment by Gingeh** [comment]
Those are placeholder instructions from the repo template, the actual instructions have not been written yet.

**Comment by VictorTennekes** [comment]
This has been solved in pr #6
