### ISSUE TITLE
Sticky Scroll lines are an ugly yellow when hovered

### ISSUE THREAD

**Issue by laurinneff** [catppuccin/vscode#50]
Example:  
![image](https://user-images.githubusercontent.com/29987831/197516424-a12ec2b7-fff5-4e88-bf42-b5bc40aa6726.png)

I changed this color (`editorStickyScrollHover.background`) to Surface0 in my user config, which looks like this on Macchiato:  
![image](https://user-images.githubusercontent.com/29987831/197516650-8f819b68-56fd-4f88-8447-1d07f7ef2a7f.png)

**Comment by sgoudham** [comment]
Hiya, thanks for reporting this! @laurinneff 

Just for my own knowledge, what exactly are _sticky lines_ in VSCode? I, unfortunately, haven't used this at all.

 In terms of the highlights, there doesn't seem to be a highlight currently in the ongoing refactor within the [`dev`](https://github.com/catppuccin/vscode/blob/2651d4503753cf4155bbb57f7e2edd150808f65c/src/theme/index.ts#L2505) branch which should make this a nice easy fix!

If anyone else reading this wants to pick this up before me, I'd imagine you'd add the following:
```diff
+ "editorStickyScrollHover.background": palette.surface0,
```

**Comment by laurinneff** [comment]
There's an option called sticky scroll that makes the definitions for things like functions/classes stick to the top of the editor, so you can quickly see what you're editing. It's not enabled by default so that's why you don't know it, but I find it quite handy.
