### ISSUE TITLE
[Feature request] Add option to disable bold text

### ISSUE THREAD

**Issue by piotrwieckiewicz** [catppuccin/vscode#55]
Similarly to option to disable italics which was added recently, maybe a good idea was to add option to disable bold text?
In some languages there are a lot of bold text 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/62888911/198650000-bfdf55c2-6ced-4de6-bedf-cb503789fbf8.png">

**Comment by nekowinston** [comment]
Sure thing, I'll work on it!

**Comment by nekowinston** [comment]
@piotrwieckiewicz I have added it, and just rolled a new release. Should be on the marketplace in a couple of minutes.

**Comment by piotrwieckiewicz** [comment]
@nekowinston Wow, thank you for such a quick fix and creating such an amazing theme!

Unfortunately, it does not work for me. If I write code in Scala, bold keywords are still a thing - even after disabling bold font in settings. I don't know, maybe thats something language-specific, although it happens ONLY with Catppuccin. In every other theme keywords are not bold.
Strange

**Comment by nekowinston** [comment]
Could you please try to toggle the setting again?

The settings toggle is pretty new, and I wouldn't be surprised if that's the cause of the issue.

**Comment by piotrwieckiewicz** [comment]
@nekowinston There is something wrong here, but I am not sure what exactly. Toggle sometimes turn bold font on of off, but sometimes it does not. And turning italics on/off sometimes breaks bold. For instance, if you have bold font turned on and if you start toggling italics, bold font might turn. It does not seems consistent, but you can create a situation where bold font is present in code, but in option it is not (and vice versa)

**Comment by nekowinston** [comment]
Yeah I just had a look at your example myself, it's definitely the compile step. I'll have a look at this again tomorrow.
![image](https://user-images.githubusercontent.com/79978224/198707200-e943f15b-96ef-4f07-8f3a-b06889e5a55a.png)
![image](https://user-images.githubusercontent.com/79978224/198707213-90239fbe-3c7d-4016-af5e-3c80b35eac5b.png)

**Comment by piotrwieckiewicz** [comment]
Good to know I'm not going crazy :D 
Thanks!

**Comment by nekowinston** [comment]
Tracking this in #61, will roll a release later.

**Comment by nekowinston** [comment]
Just following up here @piotrwieckiewicz, I just closed #61, I hope I found the main problem. Please let me know if the compile step works for you now.
