### ISSUE TITLE
Sidebar/Status bar color changed in v2.2.0

### ISSUE THREAD

**Issue by suppayami** [catppuccin/vscode#57]
The sidebar and status bar (and some other UI parts) in v2.2.0 got color changed to `crust` which looks pretty weird in Frappe and Machiato (the UI looks not so consistent and makes some UI parts "striped"). Is this intended?

![image](https://user-images.githubusercontent.com/2419328/198684613-a032063e-9aa5-48df-85a5-2e95c9678e77.png)
![image](https://user-images.githubusercontent.com/2419328/198684935-f904507d-555a-4d53-8eee-f30e58393ae7.png)

**Comment by nekowinston** [comment]
Yes. This was an intended change to reflect the style guide more closely.

**Comment by suppayami** [comment]
Thanks for clarifying! It would be nice to have a lower contrast mode to make those parts less stand out since I love the previous Machiato 😄

**Comment by nekowinston** [comment]
I'll consider it. I would appreciate some input, since I think that #54 improved shading in quite a few areas, I hope you'd agree.

Which sections specifically would you like to have to appear more "flat"? I think the crust Tab Bar background is objectively good, since you can more easily distinguish
`[Inactive Tab][Active Tab][Inactive Tab][...rest of the Tab Bar...]`

The separator between the Tab Bar & Editor would likely disappear in the "flat appearance" option?
Would you make the *whole window* (decorations, sidebar, file browser) the same color, `base`?

Any feedback is appreciated, whether it's screenshots or JSON keys for the Workbench elements.

**Comment by suppayami** [comment]
I made a PR for this, pretty WIP but basically it's the main idea of flat mode
#59

**Comment by paprikman** [comment]
I agree with @suppayami, I've always thought of catppuccin as of a flat color theme. And now it looks very weird and distracting, especially considering the document map background
![image](https://user-images.githubusercontent.com/57448756/198820985-5772eb59-353f-4cb6-ba01-fcfd0bc51080.png)

P.S. I also do not understand why other code colors (color choices for function/variable names, class methods, etc) are different from, say, catppuiccin vim and other themes.

**Comment by nekowinston** [comment]
I personally just recently started working on this theme, and don't use VSCode myself, really. I'm just trying to improve issues on this theme - so all the feedback from actual daily VSCode users is appreciated.

@paprikman 
> especially considering the document map background

Yes, that has been pointed out to me, I will change it to 50% `mantle` with the next update. With the "flat appearance" option it will be 50% `base`.

> P.S. I also do not understand why other code colors (color choices for function/variable names, class methods, etc) are different from, say, catppuiccin vim and other themes.

I have created a new issue (#62) where I link to a PR (#53) that aims to address this. I agree that our VSCode port is inconsistent and doesn't seem well thought out.

**Comment by paprikman** [comment]
> I personally just recently started working on this theme, and don't use VSCode myself, really. I'm just trying to improve issues on this theme - so all the feedback from actual daily VSCode users is appreciated.
> 
> @paprikman
> 
> > especially considering the document map background
> 
> Yes, that has been pointed out to me, I will change it to 50% opacity `mantle` with the next update. With the "flat appearance" option it will be 50% opacity `base`.
> 
> > P.S. I also do not understand why other code colors (color choices for function/variable names, class methods, etc) are different from, say, catppuiccin vim and other themes.
> 
> I have created a new issue (#62) where I link to a PR (#53) that aims to address this. I agree that our VSCode port is inconsistent and doesn't seem well thought out.

Good to know, thank you!
I'll keep an eye on that and see if I can contribute as well.
