### ISSUE TITLE
The stepover icon is hard to see on debug menu

### ISSUE THREAD

**Issue by ZHDreamer** [catppuccin/vscode#60]
![Snipaste_2022-10-29_11-11-26](https://user-images.githubusercontent.com/40716043/198801155-c75e3cd2-251b-4dd1-bf05-ea4d0c26ae0a.png)
Is that a feature or a bug? If it is a feature, how can I change it?

**Comment by nekowinston** [comment]
hey there, thanks for the issue - that's definitely not intended. i'll fix it.

**Comment by nekowinston** [comment]
I changed the stepover icon color to mauve, and rolled a new release.

**Comment by ZHDreamer** [comment]
Thank you for the fast response! It looks great now.
