### ISSUE TITLE
Feature Request: Support for Error Lens Extension

### ISSUE THREAD

**Issue by laurinneff** [catppuccin/vscode#68]
I have the Error Lens (`usernamehw.errorlens`) extension in my VSCode, and its default colors don't look great with this theme and so I've added some overrides to use Catppuccin colors instead. Would these be accepted in the upstream theme?

The overrides:

```json
{
  "errorLens.errorForeground": "red",
  "errorLens.warningForeground": "peach",
  "errorLens.hintForeground": "teal"
}
```

And also: (had to use custom hex codes for these)

```json
{
  // red/peach/teal, but with 0x22 opacity
  "errorLens.errorBackground": "#ed879622",
  "errorLens.warningBackground": "#f5a97f22",
  "errorLens.hintBackground": "#8bd5ca22"
}
```

This changes it from this:

![grafik](https://user-images.githubusercontent.com/29987831/199463374-a8fc4177-730a-458f-8040-afeaf0511b14.png)
![grafik](https://user-images.githubusercontent.com/29987831/199463322-c296caf8-87c7-4de7-a560-95fb28c3a13b.png)
![grafik](https://user-images.githubusercontent.com/29987831/199463974-a9cf8aa0-a327-4410-90e8-c3578a19ad47.png)

to this:

![grafik](https://user-images.githubusercontent.com/29987831/199464322-6bda202a-b4cc-4d0d-b466-bfa9306627fc.png)
![grafik](https://user-images.githubusercontent.com/29987831/199464435-c0ee4a94-0aff-4bb3-a2ce-6d1ed3037d97.png)
![grafik](https://user-images.githubusercontent.com/29987831/199464474-2250bf6b-1671-4250-b98e-6b86686dae22.png)

There's also an `info` error level, but I haven't found code that produces it yet so I haven't been able to find colors that are similar to the original ones while fitting in (for now I have it set to some really obvious colors so I'll be sure to notice if I ever come across code that produces it)

**Comment by nekowinston** [comment]
Hi there, thanks for your issue!

I think it makes sense to support some plugins with ~1M installs, so I'll definitely add that one.

> And also: (had to use custom hex codes for these)

The latest update added helper functions, so you can actually let the theme generate them for each flavour! Works like this:

```json5
    "catppuccin.customUIColors": {
        "all": {
            "errorLens.errorBackground": "red 0.15",
            "errorLens.warningForeground": "peach 0.15",
            "errorLens.hintForeground": "teal 0.15",
        },
    }
```

See [Use palette colours on workbench elements](https://github.com/catppuccin/vscode#use-palette-colours-on-workbench-elements-ui) for the docs!

**Comment by laurinneff** [comment]
Thanks for the hint about custom opacity! I hadn't noticed that part of the docs when I noticed that UI color overrides were added.
