### ISSUE TITLE
Sticky scroll has no shadow

### ISSUE THREAD

**Issue by eero-lehtinen** [catppuccin/vscode#72]
The default dark+ theme has a shadow for distinguishing sticky scroll from other content.
![Screenshot 2022-11-03 160644](https://user-images.githubusercontent.com/7013023/199743899-93c20c07-100e-4938-b262-286fe8ba0186.png)

This theme currently does not.
![Screenshot 2022-11-03 160751](https://user-images.githubusercontent.com/7013023/199744191-87e1a708-30c8-4639-a851-e7471265a9e5.png)

It can be enabled by setting "scrollbar.shadow" to a color. Below is an example of it being #00000080. In dark+, it's set to full black.
![Screenshot 2022-11-03 160725](https://user-images.githubusercontent.com/7013023/199744155-8962d9bd-1428-48dd-8edc-f95c0914c413.png)

It also adds a shadow to the scrollbar, but there seems to be no way to prevent that.

**Comment by nekowinston** [comment]
Asking @suppayami since @nullchilly opened a PR #77:

What's your take on shadows in the flat appearance? Since they also show up in Peek views, etc.

**Comment by suppayami** [comment]
Hi, I think a soft shadow would work well here for clarity, though putting shadow on peek views looks not really good. I think we can either put this as an option, or see if we can change the bg color for sticky contents

**Comment by nekowinston** [comment]
> Hi, I think a soft shadow would work well here for clarity, though putting shadow on peek views looks not really good. I think we can either put this as an option, or see if we can change the bg color for sticky contents

Since the shadow shows up on all places by default in VSCode (without custom CSS), I just changed the color for the shadow to `mantle` in the flat appearance, keeping the philosophy of only using 2 shades (base/mantle). If people care enough, they can override it with our `catppuccin.customUIColors`; not really interested in adding switches for every little thing 🙂
