### ISSUE TITLE
[Feature] support vscode for web

### ISSUE THREAD

**Issue by Weilet** [catppuccin/vscode#74]
Below are some infomation for web extensions:
https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-anatomy

**Comment by Weilet** [comment]
I try to simply add an entry for browser: #75 
I am not familiar with vscode plugin so I do not know if my PR is right. Correct me if I am wrong.

**Comment by nekowinston** [comment]
On my To-Do list for 2.6.0.
