### ISSUE TITLE
Include standard themes in repository without build step

### ISSUE THREAD

**Issue by Abdisalan** [catppuccin/vscode#78]
## Idea
Introduce a top level folder `default-themes` with theme files `frappe.json`, `latte.json`, `macchiato.json`, and `mocha.json`.
## Motivation
I'd like to use this theme at work but they're really strict about using scripts but are okay with themes and I'd like to keep attribution towards this project (using the github repo link rather than just copying over the files).

**Comment by nekowinston** [comment]
Hi there! We provide the themes in [our releases](https://github.com/catppuccin/vscode/releases/latest), too!

The VSIX is just a file which you can unzip, it contains all four flavours (with default settings):
<img width="587" alt="image" src="https://user-images.githubusercontent.com/79978224/206886918-886ccda9-1184-4146-b6bc-cbc92b4bf01d.png">

We're not keeping the compiled files on the main branch, but I guess we could create an orphaned branch where the CI auto-publishes them?

**Comment by Abdisalan** [comment]
Thanks for the prompt response!

On my end, it looks like using an orphaned branch would be the fastest to integrate. If you can add that, that'd be really great! 😃

**Comment by nekowinston** [comment]
The CI now builds the [`compiled`](https://github.com/catppuccin/vscode/tree/compiled) branch on tagged releases, following the VSCode marketplace and OpenVSX. I just rolled a new release, the branch should be live in a second.
