### ISSUE TITLE
Apply accentColor of the theme to more properties

### ISSUE THREAD

**Issue by hamelhmc** [catppuccin/vscode#84]
`"catppuccin.accentColor": "sky",`
 
Currently, the accentColor of the theme is only applied to certain properties. However, I believe it would be useful to extend its use to other properties to create a more coherent user experience.

As an example, I propose applying the accentColor "sky" (#87ceeb) to the following properties:

```json
  "workbench.colorCustomizations": {
    "editorCursor.foreground": "#87ceeb",
    "editorBracketHighlight.foreground1": "#87ceeb",
    "tab.activeBorder": "#87ceeb",
    "tab.activeBorderTop": "#87ceeb",
    "terminalCursor.foreground": "#87ceeb",
  },
```

By doing this, all visual elements related to the accentColor would look coherent and help users quickly identify important elements in the interface.

Could someone review this suggestion and consider it for a future update? Thank you!

**Comment by nekowinston** [comment]
Thanks for the suggestions.
Tabs sound like a good idea, but I'm hesitant to touch the cursors - they're following the [Catppuccin spec](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#window-colours), and [documentation is provided](https://github.com/catppuccin/vscode#use-palette-colours-on-workbench-elements-ui) on how to override keys. You can use `accent` to set them to your accent color.

`editorBracketHighlight.foreground1`: there are already [4 different ways to color the brackets](https://github.com/catppuccin/vscode#paired-brackets), if users want to fine tune it, the mentioned docs exist.

**Comment by nekowinston** [comment]
> Tabs sound like a good idea

I just noticed a month later that we're already styling them in the `accent` color.
Since you can use `accent` anywhere else you please with [this setting](https://github.com/catppuccin/vscode#use-palette-colors-on-workbench-elements-ui), I'll mark this as closed.
