### ISSUE TITLE
2.6.0 Update breaks accent colors

### ISSUE THREAD

**Issue by sthurston99** [catppuccin/vscode#89]
When updating from extension version 2.5.0 to 2.6.0, the accent color reverts from what was set (i.e. Sapphire for me), to the default Mauve. This does not affect the setting, merely changing the color, and updating the setting to any other accent color does not change it.
![image](https://user-images.githubusercontent.com/44074551/216675637-fddf2519-33cb-4a9d-918d-c98832ab78f1.png)

**Comment by sthurston99** [comment]
Attached: My settings.json to confirm the accent setting is properly set. https://pastebin.com/p1HckuFv

**Comment by sthurston99** [comment]
I've gotten the prompt when upgrading to the new version, and reloaded multiple times when testing. I'm currently using VSCodium 1.74.3 Release 23010, the newest available through winget, on Windows 11 22H2, which hasn't really affected much. Reverting back to extension version 2.5.0 correctly loads the accent colorscheme.

**Comment by nekowinston** [comment]
This is interesting, since I didn't touch the logic of the compile function at all: https://github.com/catppuccin/vscode/compare/v2.5.0...v2.6.0

I'd need someone else to try this on Windows for me - I'm on the same release on Mac. At the moment I don't exactly know how to help with troubleshooting this...
Could you try deleting the Extension directory locally, then reinstalling 2.6.0? There might be some undiscovered bug with our compile function.

**Comment by sthurston99** [comment]
Used the uninstall function within VSCodium, deleted the catppuccin extension caches from %Appdata%\VSCodium\CachedExtensionVSIXs, then restarted VSCodium and reinstalled from the market. Still has the issue.
![image](https://user-images.githubusercontent.com/44074551/216681890-765fa9d5-46d8-462f-91fd-9068eff09962.png)

**Comment by nekowinston** [comment]
Oh interesting, I didn't know about the folder structure on Windows.

On Mac/Linux, there is an uncompressed copy of the VSIX in: `~/.vscode/extensions/catppuccin.catppuccin-vsc-2.6.0`, where an empty `themes/.flag` is created, and the re-compiled files are kept.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/79978224/216683132-152bce2a-b8c9-4278-a1fc-db945e0b946c.png">

Deleting those cached theme JSONs should forcefully recompile them all.

**Comment by sthurston99** [comment]
Ok yep! That seemed to do it. After clearing that folder version of the extension, it properly applied the accent on reload.

Not sure what would have caused that but this should be good to close.

**Comment by nekowinston** [comment]
Glad this could fix it!
Still unsure why it happened, usually the extension would just overwrite the files when needed.

**Comment by codeonblocks** [comment]
Im having this same issue.
