### ISSUE TITLE
Add option to enable borders in "catppuccin" theme

### ISSUE THREAD

**Issue by hamelhmc** [catppuccin/vscode#92]
Hi,

I would like to suggest adding an option in the "catppuccin" theme to enable borders on various UI elements, as shown in the following manual example:

```json
"workbench.colorCustomizations": {
    "activityBar.border": "#ffffff15",
    "button.secondaryHoverBackground": "#ffffff15",
    "checkbox.border": "#ffffff15",
    "editorGroupHeader.tabsBorder": "#ffffff15",
    "panel.border": "#ffffff15",
    "panelInput.border": "#ffffff15",
    "sideBar.border": "#ffffff15",
    "sideBarSectionHeader.border": "#ffffff15",
    "statusBar.border": "#ffffff15",
    "tab.border": "#ffffff15",
    "tab.unfocusedActiveBorderTop": "#ffffff15",
    "titleBar.border": "#ffffff15"
}
```
Currently, it's possible to customize the colors of various UI elements in the "settings.json" configuration file using the "workbench.colorCustomizations" property. However, this option does not include the ability to enable or disable borders. The ability to enable borders could be useful for users who want a more defined and contrasted UI.

Therefore, I suggest adding the "catppuccin.activeBorder" option in the "catppuccin" theme to allow users to enable or disable borders on various UI elements.

Thank you for considering this suggestion.

**Comment by GhIlyusha** [comment]
I would really appreciate a bordered variant. It'd make it way easier to navigate the interface with this theme.
These two are good examples of bordered themes:
https://github.com/moegi-design/vscode-theme
https://github.com/ayu-theme/vscode-ayu
