### ISSUE TITLE
Syntax highlighting for ddl files

### ISSUE THREAD

**Issue by HarshitSohaney** [catppuccin/vscode#95]
Catppuccin v2.7.0
- There seems to be no syntax highlighting for .ddl files 
- It appears like a plain text file
- Requesting to update and add syntax highlighting for .ddl files

**Comment by nekowinston** [comment]
It seems like DDL
- doesn't have a syntax parser in VSCode, hence it will appear as plaintext
- looks fine if you select `SQL` in Ctrl+Shift+P `Select Language Mode`.
